{% extends "common/mobile-index.phtml" %}
{% block title  %}金职夺宝 - {{ data['list']['name'] }}{% endblock %}
{% block header %}
	<meta name="description" content="{{ data['list']['name'] }}">
{% endblock %}
{% block css %}{{ stylesheetLink('css/db/db.css') }}{% endblock %}
{% block content %}
<style type="text/css">
	.mui-preview-image.mui-fullscreen {
		position: fixed;
		z-index: 20;
		background-color: #000;
	}
	.mui-preview-header,
	.mui-preview-footer {
		position: absolute;
		width: 100%;
		left: 0;
		z-index: 10;
	}
	.mui-preview-header {
		height: 44px;
		top: 0;
	}
	.mui-preview-footer {
		height: 50px;
		bottom: 0px;
	}
	.mui-preview-header .mui-preview-indicator {
		display: block;
		line-height: 25px;
		color: #fff;
		text-align: center;
		margin: 15px auto 4;
		width: 70px;
		background-color: rgba(0, 0, 0, 0.4);
		border-radius: 12px;
		font-size: 16px;
	}
	.mui-preview-image {
		display: none;
		-webkit-animation-duration: 0.5s;
		animation-duration: 0.5s;
		-webkit-animation-fill-mode: both;
		animation-fill-mode: both;
	}
	.mui-preview-image.mui-preview-in {
		-webkit-animation-name: fadeIn;
		animation-name: fadeIn;
	}
	.mui-preview-image.mui-preview-out {
		background: none;
		-webkit-animation-name: fadeOut;
		animation-name: fadeOut;
	}
	.mui-preview-image.mui-preview-out .mui-preview-header,
	.mui-preview-image.mui-preview-out .mui-preview-footer {
		display: none;
	}
	.mui-zoom-scroller {
		position: absolute;
		display: -webkit-box;
		display: -webkit-flex;
		display: flex;
		-webkit-box-align: center;
		-webkit-align-items: center;
		align-items: center;
		-webkit-box-pack: center;
		-webkit-justify-content: center;
		justify-content: center;
		left: 0;
		right: 0;
		bottom: 0;
		top: 0;
		width: 100%;
		height: 100%;
		margin: 0;
		-webkit-backface-visibility: hidden;
	}
	.mui-zoom {
		-webkit-transform-style: preserve-3d;
		transform-style: preserve-3d;
	}
	.mui-slider .mui-slider-group .mui-slider-item img {
		width: auto;
		height: auto;
		max-width: 100%;
		max-height: 100%;
	}
	.mui-android-4-1 .mui-slider .mui-slider-group .mui-slider-item img {
		width: 100%;
	}
	.mui-android-4-1 .mui-slider.mui-preview-image .mui-slider-group .mui-slider-item {
		display: inline-table;
	}
	.mui-android-4-1 .mui-slider.mui-preview-image .mui-zoom-scroller img {
		display: table-cell;
		vertical-align: middle;
	}
	.mui-preview-loading {
		position: absolute;
		width: 100%;
		height: 100%;
		top: 0;
		left: 0;
		display: none;
	}
	.mui-preview-loading.mui-active {
		display: block;
	}
	.mui-preview-loading .mui-spinner-white {
		position: absolute;
		top: 50%;
		left: 50%;
		margin-left: -25px;
		margin-top: -25px;
		height: 50px;
		width: 50px;
	}
	.mui-preview-image img.mui-transitioning {
		-webkit-transition: -webkit-transform 0.5s ease, opacity 0.5s ease;
		transition: transform 0.5s ease, opacity 0.5s ease;
	}
	@-webkit-keyframes fadeIn {
		0% {
			opacity: 0;
		}
		100% {
			opacity: 1;
		}
	}
	@keyframes fadeIn {
		0% {
			opacity: 0;
		}
		100% {
			opacity: 1;
		}
	}
	@-webkit-keyframes fadeOut {
		0% {
			opacity: 1;
		}
		100% {
			opacity: 0;
		}
	}
	@keyframes fadeOut {
		0% {
			opacity: 1;
		}
		100% {
			opacity: 0;
		}
	}
</style>
<style type="text/css">
	#slider {
		/*height: 34.2rem;*/
		height: 25.2rem;
	}
	.itembox {
		/*height: 34.2rem !important;*/
		height: 25.2rem !important;
		background: #fff;
	}
	.itembox a {
		width: 100%;
    	height: 100%;
	}
	.mui-slider-indicator .mui-indicator {
	    margin: 1px 2px;
	    background: #fff;
	}
	.mui-slider-indicator .mui-active.mui-indicator {
		background: #1f36bf;
	}
	.container > .row {
		margin-bottom: 1rem;
		padding:1rem;
		border-top: 1px solid #eee;
		color:#67686e;
		background: #fff;
		font-size: 1rem;
	}
	.info .title {	
		line-height: 1.68rem;
		font-size:1.14rem;
		overflow: hidden;	
	}
	.info .title .tips {
		background: #fbb73c;
		display: inline-block;
		width: 5.5rem;
		height: 1.52rem;
		line-height: 1.58rem;
		color:#fff;
		text-align: center;
		margin-right: 5px;
		border-radius: 1.52rem;
	}
	.info .progressbox .person {
		margin-top:.8rem;
		color:#a4a6ad;
		font-size: 1rem;
	}
	.info .progressbox .progressrow {
		width: 100%;
		height: 5px;
		background: #d7dae7;
		border-radius: 5px;
		position:relative;
		margin-bottom: 5px;
	}
	.info .progressbox .progress {
		position: absolute;
		top:0;
		left:0;
		height: 5px;
		border-radius: 5px;
	}
	.info .progressbox .consume::before {
		content: "";
	    background: url(/public/img/db/coin.png) center no-repeat;
	    background-size: contain;
        width: 1rem;
	    height: 1.4rem;
	    position: absolute;
	    top: -.1rem;
	    left: -1.5rem;
	    display: block;
	}
	.info .winningbox {
		border-top:1px solid #eee;
		padding-top:8px;
		margin-top: .8rem;
	}
	.info .winnerrow .head {
		width: 24%;
		height: 5.7rem;
		position: relative;
		margin-right: 6%;
	}
	.info .winnerrow .head .imgbox {
		width: 5.7rem;
		height: 5.7rem;
		border-radius: 50%;
		background: #fbb73c;
		overflow: hidden;
		position: relative;
	}
	.info .winnerrow .head .imgbox span {
		display: inline-block;
		width: 70%;
		height: 50%;
		line-height: .9;
		font-size:3rem;
		text-align: center;
		color:#fff;
		font-family: "黑体";
	}
	.info .winnerrow .head .tip {
		width: 100%;
		height: 1.84rem;
		position: absolute;
		left: 0;
		bottom: 0;
	}
	.info .winnerrow .userinfo {
		/*width: 68%;*/
		/*height: 5.7rem;*/
		font-size:1.14rem;
	}
	.info .winnerrow .userinfo p {
		margin: 0;
		line-height: 1.6rem;
		color:#717278;
		font-size:1rem;
	}
	.info .winnerrow .userinfo p span.tit {
		display: inline-block;
		width:6.4rem;
		text-align: right;
		color:#a4a6ad;
	}
	.info .winnerrow .userinfo p span.pink {
		color:#ff2a63;
		display: inline-block;
		margin-right: 2px;
	}
	.info .winningbox a.link {
		width: 9.18rem;
		height: 2.34rem;
		line-height: 2.34rem;
		border-radius: 2.34rem;
		color:#fff;
		font-size: 1.14rem;
		display: block;
		margin:0 auto;
		margin-top:8px;
		text-align: center;
	}
	.joined.mui-table-view-cell.mui-active {
		background: #fff;
	}
	.joined a .num {
		color:#ff2a63;
	}
	.joined a .right {
		margin-right: 20px;
		color:#a4a6ad;
	}
	.joined .code {
		padding:2rem 1rem;
		font-size:3rem;
		color:#ff2a63;
		text-align: center;
		border-top: 1px solid #eee;
		/*word-wrap: break-word;
    	word-break: break-all;*/
    	overflow: auto !important;
	}
	.mui-segmented-control {
		border:none;
		border-bottom: 1px solid #eee;
	}
	.mui-segmented-control .mui-control-item {
		border: none;
		color:#67686e;
		text-decoration: none;
		line-height: 2.5rem;
		font-size: 1.14rem;
	}
	.mui-segmented-control .mui-control-item.mui-active {
		border:none;
		color:#67686e;
		background-color:transparent;
		position: relative;
	}
	.mui-segmented-control .mui-control-item.mui-active::after {
		content: "";
	    background: -webkit-linear-gradient(left, #ff0a8d , #ff5d24); /* Safari 5.1 - 6.0 */
		background: -o-linear-gradient(right, #ff0a8d, #ff5d24); /* Opera 11.1 - 12.0 */
		background: -moz-linear-gradient(right, #ff0a8d, #ff5d24); /* Firefox 3.6 - 15 */
		background: linear-gradient(to right, #ff0a8d , #ff5d24); /* 标准的语法 */
	    background-size: contain;
        width: 100%;
	    height: 2px;
	    position: absolute;
	    left: 0;
	    bottom: 0;
	    display: block;
	}
	.feedbackbox {
		margin-bottom: 9rem;
	}
	.comment {
		position: relative;
		overflow: hidden;
		margin-bottom: 10px;
	}
	.comment::after {
		content: "";
		background: #eee;
		width: 110%;
	    height: 10px;
	    margin-left: -15px;
	    margin-right: -15px;
	    position: absolute;
	    left: 0;
	    bottom: -5px;
	    display: block;
	}
	.comment .userinfo {
		margin:.8rem 0;
		height: 2.85rem;
		line-height: 2.85rem;
		color:#67686e;
		font-size:1.14rem;
		position: relative;
	}
	.comment .userinfo .user .username {
		width: 2.85rem;
		height: 2.85rem;
		border-radius: 50%;
		margin-right: .5rem;
		display: inline-block;
		text-align: center;
		color:#fff;
		font-family: "黑体";
		background: #fbb73c;
		font-size:2rem;
		float:left;
	}
	.comment .userinfo .time {
		color:#a4a6ad;
	}
	.comment p {
		font-size: 1rem;
		color:#67686e;
		line-height: 1.8rem;
		width: 100%;
	    height: auto;
	    word-wrap: break-word;
	    word-break: break-all;
	    overflow: hidden;
	}
	.comment .picturerow {
		width: 107%;
	}
	.comment .picturerow .rel {
		height:6rem;
		width: 20%;
		margin-right: 4%;
		margin-bottom: 10px;
		padding:2px;
		border:1px solid #eee;
		float:left;
	}
	.comment .picturerow .rel img {
		max-width: 98%;
		max-height: 98%;
	}
	.comment hr {
		margin-top:0;
		margin-bottom: 5px;
	}
	.comment .itemlink {
		color:#a4a6ad;
		font-size: 1rem;
		display: block;
		text-decoration: none;
		padding-bottom: 1rem;
	}
	#buy {
		width: 80%;
	    height: 3.62rem;
	    line-height: 3.62rem;
	    border-radius: 3.62rem;
	    color: #fff;
	    text-align: center;
	    font-size: 2rem;
	    position: fixed;
	    bottom: 6.82rem;
	    left: 10%;
	    right: 10%;
	    z-index: 10;
	}
	#mask {
		position: fixed;
		top:0;
		left:0;
		width: 100%;
		height: 100%;
		z-index: 20;
		background: rgba(0,0,0,0.7);
		display: none;
	}
	.buybox {
		position: absolute;
		bottom: 5.82rem;
		left:0;
		background: #fff;
		width: 100%;
		/*height: 21rem;*/
	}
	.buybox .tit {
		padding:10px;
		border-bottom: 1px solid #eee;
		text-align: center;
		font-size: 1.58rem;
		color:#67686e;
		height: 3.68rem;
	}
	.buybox .tit .left {
		display: inline-block;
		font-size: 1.58rem;
		width: 1.2rem;
		height: 100%;
		margin-left:5px;
		background: url(/public/img/db/close.png) center no-repeat;
		background-size: contain;
	}
	#Buynow {
		font-size: 1.58rem;
		color:#ff2a63;
		margin-right: 5px;
		padding:0;
	}
	.buybox .container {
		font-size: 1.4rem;
	}
	.buybox .rows {
		padding:10px 0;
	}
	.buybox .payinfo {
		color:#a4a6ad;
		border-bottom: 1px solid #eee;
	}
	.buybox .payinfo .right {
		color:#67686e;
	}
	.buybox .need span {
		color:#ff2a63;
	}
	#bottomPopover {
		height: 13rem !important;
		bottom: 16rem !important;
		left: auto !important;
    	right: 1rem !important;
    	width: 50% !important;
	}
	.mui-popover .mui-popover-arrow {
		right:1rem !important;
	}
	.mui-numbox {
		width: 100%;
		border: solid 1px #eee;
	}
	.mui-numbox [class*=btn-numbox] {
		font-size:2rem;
	}
	.mui-numbox .mui-input-numbox {
		border-right: solid 1px #eee!important;
    	border-left: solid 1px #eee!important;
	}
	.selectnun {
		width: 105.2%;
	}
	.selectnun .col-xs-3 {
		width: 20%;
		margin-right: 5%;
		border: solid 1px #eee;
	}
	.joinrecord .mui-table-view-cell {
		padding:5px 0;
	}
	.joinrecord .mui-table-view-cell::after{
		margin-left: -15px;
	}
	.joinrecord .joinrow {
		height: 3.8rem;
	}
	.joinrecord .joinrow .head {
		/*width: 3.8rem;
		margin-right: 1rem;*/
		width: 15%;
		margin-right: 5%;
		/*height: 3.8rem;*/
		border-radius: 50%;
		overflow: hidden;
		position: relative;
	}
	.joinrecord .joinrow .head .username {
		width: 100%;
		height: 100%;
		line-height: 2.3;
		border-radius: 50%;
		margin-right: .5rem;
		display: inline-block;
		text-align: center;
		color:#fff;
		font-family: "黑体";
		background: #fbb73c;
		font-size:2rem;
		float:left;
	}
	.joinrecord .joinrow .info {
		width: 80%;
		padding: 5px 0;
		color:#a4a6ad;
		font-size:1rem;
	}
	.joinrecord .joinrow .info > div {
		padding:2px 0;
	}
	.joinrecord .joinrow .info .name {
		color:#4a4b4e;
		font-size:1.14rem;
	}
	.joinrecord .joinrow .info span {
		color:#ff2a63;
	}
	p.rules {
		font-size:1.14rem;
		color:#4a4b4e;
		line-height: 2rem;
		padding:10px 0;
	}
	p.rules span {
		color:#ff2a63;
	}
	header .mui-pull-right span.share {
		position: relative;
	    width: 2rem;
	    height: 100%;
	    display: inline-block;
	}
</style>

<!--微信接口-分享-->
<script src="http://res.wx.qq.com/open/js/jweixin-1.2.0.js" type="text/javascript"></script>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">商品详情</h1>
	<a class="mui-pull-right"><span class="share" id="Share"><img src="/public/img/db/share.png" class="auto-center"></span></a>
</header>

<div class="mui-content">
	<div id="slider" class="mui-slider">
		<div class="mui-slider-group mui-slider-loop">
			<div class="mui-slider-item itembox mui-slider-item-duplicate">
				<a href="#">
					<img src="{{ data['list']['imgs2'][0] }}" class="auto-center">
				</a>
			</div>
			{% for key, item in data['list']['imgs'] %}
				<div class="mui-slider-item itembox">
					<a href="#">
						<img src="{{ item }}" class="auto-center" data-preview-src=""  data-preview-group="A">
					</a>
				</div>
			{% endfor %}
			<div class="mui-slider-item itembox mui-slider-item-duplicate">
				<a href="#">
					<img src="{{ data['list']['imgs2'][1] }}" class="auto-center">
				</a>
			</div>
		</div>
		<div class="mui-slider-indicator">
			{% for key, item in data['list']['imgs'] %}
				{% if key == 0 %}
					<div class="mui-indicator mui-active"></div>
				{% else%}
					<div class="mui-indicator"></div>
				{% endif %}
			{% endfor %}
		</div>
	</div>
	<div class="container">
		<div class="row info">
			<div class="title">
				<span class="tips">{{ data['list']['no'] }}期</span>
				{{ data['list']['name'] }}
			</div>
			{% if data['list']['is_end'] == 'Y' %}
				<div class="winningbox">
					<div class="winnerrow">
						<div class="head left">
							<div class="imgbox auto-center"><span class="winnername auto-center">{{ data['list']['username'] }}</span></div>
							<div class="tip"><img src="/public/img/db/winner.png" class="auto-center"></div>
						</div>
						<div class="userinfo left">
							<p><span class="tit">获奖者：</span>{{ data['list']['phone'] }}</p>
							<p><span class="tit">本期参与：</span><span class="pink">{{ data['list']['already_num'] }}</span>人次</p>
							<p><span class="tit">幸运号码：</span><span class="pink">{{ data['list']['lucky_num'] }}</span></p>
							<p><span class="tit">揭晓时间：</span>{{ data['list']['end_time'] }}</p>
						</div>
						<div class="cls"></div>
					</div>
					<a href="/db/luckynum/{{ data['list']['id'] }}" class="link gradual">查看幸运号码</a>
				</div>
			{% else %}
				<div class="progressbox">
					<div class="person">
						<div class="left">总需<span>{{ data['list']['need_num'] }}</span>人次</div>
						<div class="right">剩余<span>{{ data['list']['has_num'] }}</span>人次</div>
						<div class="cls"></div>
					</div>
					<div class="progressrow">
						<div class="progress gradual" style="width:{{ data['list']['percent'] }}%"></div>
					</div>
					<div class="consume right rel"><span>50</span>JOB币/人次</div>
				</div>
			{% endif %}
		</div>
		{% if data['listusertotal'] %}
			<div class="row record joined mui-collapse mui-table-view-cell">
				<a class="mui-navigate-right" href="#">夺宝记录：我参与了<span class="num">{{ data['listusertotal'] }}</span>次<span class="right">持有码</span></a>
				<div class="mui-collapse-content code">{{ data['userno'] }}</div>
			</div>
		{% else %}
			<div class="row record nojoin">
				夺宝记录：本期未参与
			</div>
		{% endif %}
		<div class="row feedback">
			<div id="segmentedControl" class="mui-segmented-control">
				<a href="#item1" class="mui-control-item mui-active">用户晒单</a>
				<a href="#item2" class="mui-control-item">参与记录</a>
				<a href="#item3" class="mui-control-item">活动规则</a>
			</div>
			<div class="feedbackbox">
				<div id="item1" class="mui-control-content mui-active">
					{% if data['listusercomment'] %}
						{% for key, item in data['listusercomment'] %}
							<div class="comment">
								<div class="userinfo">
									<div class="user left">
										<span class="username">{{ item['username'] }}</span>{{ item['phone'] }}
									</div>
									<div class="time right">{{ item['create_time'] }}</div>
								</div>
								<p>
									{{ item['comment'] }}
								</p>
								<div class="picturerow">
									{% for key2, item2 in item['imgs'] %}
										<div class="rel">
											<img src="{{ item2 }}" class="auto-center" data-preview-src=""  data-preview-group="{{ key }}">
										</div>
									{% endfor %}
									<div class="cls"></div>
								</div>
								<hr>
								<a href="/db/detail/{{ item['list_id'] }}" class="itemlink">{{ item['pname'] }}</a>
							</div>
						{% endfor %}
					{% else %}
						<div class="noneshow">暂无用户晒单。</div>
					{% endif %}
				</div>
				<div id="item2" class="mui-control-content">
					{% if data['listuser'] %}
						<ul class="mui-table-view joinrecord">
							{% for key, item in data['listuser'] %}
								<li class="mui-table-view-cell">
									<div class="joinrow">
										<div class="head left">
											<span class="username">{{ item['username'] }}</span>
										</div>
										<div class="info right">
											<div>
												<div class="left name">{{ item['phone'] }}</div>
												<div class="right">IP:{{ item['ip'] }}</div>
												<div class="cls"></div>
											</div>
											<div>
												<div class="left">参与了<span>{{ item['count'] }}</span>人次</div>
												<div class="right">{{ item['create_time'] }}</div>
												<div class="cls"></div>
											</div>
										</div>
									</div>
								</li>
							{% endfor %}
						</ul>
					{% else %}
						<div class="noneshow">暂无参与记录。</div>
					{% endif %}
				</div>
				<div id="item3" class="mui-control-content">
					<p class="rules">
						1.用户使用数字资产(JOB币)购买夺宝人次，每购买1人次，将获得1个系统分配的夺宝号码。<br>2.当该商品的全部夺宝号码分配完毕后，区块链夺宝程序将自动计算出一个幸运号码(计算规则见下一条)，持有该幸运号码的用户可直接获得该商品。<br>3.计算规则：如下图所示，当夺宝号码售罄时，系统会记录下当前eos区块链最新的区块号，同时等待幸运区块号的生成(售罄区块号+50)。待幸运区块号确认后(大约3-5分钟)，取幸运区块号签名(哈希值)的最后7位，转成10进制数字，基于夺宝总人次进行取余，得到的数字即为幸运号码。 <span>(由于区块哈希值为随机数，无法人为干预，所以保证了幸运号码的随机性和公正性)</span><br>4.金职岛保留对夺宝玩法的最终解释权。
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

{% if data['list']['is_end'] != 'Y' %}
<a href="#" class="gradual" id="buy">立即购买</a>
{% endif %}

<div id="mask">
	<div class="buybox">
		<div class="tit">
			<a class="left" id="close"></a>
			确认购买
			<a href="#" class="right btn" id="Buynow">购买</a>
		</div>
		<div class="container">
			<div class="rows payinfo">
				支付类型
				<span class="right" id="Balance" data-bal="{{ data['list']['jobcoin'] }}">JOB(余额：{{ data['list']['jobcoin'] }})</span>
			</div>
			<div class="rows payinfo rel">
				支付方式
				<!-- <a href="#bottomPopover" class="right">余额 > </a> -->
				<span class="right">余额</span>
			</div>
			<div class="rows need">
				需要 <span id="Need" data-price="50" data-need="50">50</span> JOB (50JOB/人次)
			</div>
			<div class="rows" style="padding:0">
				<div class="mui-numbox" data-numbox-min="1" data-numbox-max="{{ data['list']['has_num'] }}">
					<button class="mui-btn mui-btn-numbox-minus" type="button">-</button>
					<input class="mui-input-numbox" type="number" id="buyNum" value="1">
					<button class="mui-btn mui-btn-numbox-plus" type="button">+</button>
				</div>
			</div>
			<div class="rows selectnun">
				<input class="col-xs-3 btn" type="button" value="5" data-value="5">
				<input class="col-xs-3 btn" type="button" value="10" data-value="10">
				<input class="col-xs-3 btn" type="button" value="50" data-value="50">
				<input class="col-xs-3 btn" type="button" value="包尾" data-value="{{ data['list']['has_num'] }}" id="Maxnum">
				<div class="cls"></div>
			</div>
		</div>
	</div>
</div>

<div id="bottomPopover" class="mui-popover mui-popover-bottom">
	<div class="mui-popover-arrow"></div>
	<div class="mui-scroll-wrapper">sadsdsa</div>
</div>

<!-- <footer>
	<a href="/mjob/main" class="col-xs-4">
		<span class="icon-1 iconpng"></span>
		<span class="mui-tab-label">数据挖矿</span>
	</a>
	<a href="/mjob/main" class="col-xs-4 active">
		<span class="icon-2 iconpng"></span>
		<span class="mui-tab-label">金职岛</span>
	</a>
	<a href="/mjob/main" class="col-xs-4">
		<span class="icon-3 iconpng"></span>
		<span class="mui-tab-label">我的身份</span>
	</a>
</footer> -->

<script src="/public/js/db/mui.zoom.js"></script>
<script src="/public/js/db/mui.previewimage.js"></script>

<script type="text/javascript">

	$(window).scroll(function() {
		if($('footer').hasClass('hiddened')){
			console.log("232321")
			$("#buy").css('bottom','1.82rem');
			$(".buybox").css('bottom','0');
		} else {
			console.log("AAA")
			$("#buy").css('bottom','6.82rem');
			$(".buybox").css('bottom','5.82rem');
		}
	});

	var userid = "{{ userinfo['id'] }}";
	var hasnum = "{{ data['list']['has_num'] }}";

	$(function(){

		$('span.winnername').each(function(){
			var text = $(this).text();
			if(text != ''){
				$(this).html(text.substring(0,1));
			} else {
				$(this).html('赢');
			}
		});

		$('span.username').each(function(){
			var text = $(this).text();
			if(text != ''){
				$(this).html(text.substring(0,1));
			} else {
				$(this).html('无');
			}
		});

		$('.selectnun .btn').each(function(){
			var num = parseInt($(this).attr("data-value"));
			if(num > hasnum){
				$(this).attr('disabled',true);
			}
		});
	});

	$('#buy').on('tap',function(){
		if(userid != '') {
			setTimeout("$('#mask').fadeIn(200)",10);
		} else {
			var href = '/mjob/login?backurl='+window.location.href;
			layer.msg("客官您尚未登录，请先登录",{icon: 5,time:3000});
			setTimeout("window.location.href='" + href + "'",3000);
		}
	});

	$("#close").on('tap',function(){
		$('#mask').fadeOut(200);
	});

	$('.mui-numbox button').on('tap',function(){
		setTimeout("changeMoney()",10);
	});

	function checknum(num){
		if(num == hasnum){
			$('.mui-btn-numbox-plus').attr('disabled',true);
			$('.mui-btn-numbox-minus').attr('disabled',false);
		}
		if(num < hasnum){
			$('.mui-btn-numbox-plus').attr('disabled',false);
			$('.mui-btn-numbox-minus').attr('disabled',false);
		}
	}

	$('.selectnun .btn').on('tap',function(){
		var val = $(this).attr("data-value");
		$('#buyNum').val(val);
		checknum(val);
		//$('.mui-btn-numbox-minus').attr('disabled',false);
		changeMoney();
	});

	// $("#Maxnum").on('tap',function(){
	// 	$('.mui-btn-numbox-plus').attr('disabled',true);
	// });

	function changeMoney(){
		var price = $('#Need').attr('data-price');
		var num = $('#buyNum').val();
		var need = price * num;
		$('#Need').attr('data-need',need);
		$('#Need').html(need);
	}

	$('#Buynow').on('tap',function(){
		var _this = $(this);
		_this.attr('disabled',true);
		var balance = parseFloat($('#Balance').attr('data-bal'));
		var need = parseFloat($('#Need').attr('data-need'));
		var buynum = $("#buyNum").val();
		if(balance >= need){
			var urlArr = window.location.href.split('/');
    		var list_id = urlArr[5];
    		var btnArray = ['再想想', '买买买'];
			mui.confirm("确定以"+need+"JOB币的价格购买？", '购买确认', btnArray, function(e) {
				if (e.index == 1) {
					$(".mui-popup.mui-popup-in").hide();
					layer.load(1, {
						shade: [0.6,'#000'] //0.1透明度的白色背景
					});
					$.get("/db/buycount",{"list_id":list_id ,"jobcoin":need},function(data){
		    			if(data.error_code == "0"){
		    				window.location.href = "/db/paysuccess?num="+buynum;
		    			} else {
		    				layer.msg(data.reason,{icon: 5,time:3000});
		    				_this.attr('disabled',false);
		    			}
		    		},'json');
				} else {
					_this.attr('disabled',false);
				}
			})
		} else {
			var btnArray = ['取消', '去看看'];
			mui.confirm('查看提升余额攻略？', '当前JOB币余额不足', btnArray, function(e) {
				if (e.index == 1) {
					window.location.href = "/db/strategy";
				} else {
					_this.attr('disabled',false);
				}
			})
		}
	});

	mui('.winningbox').on('tap','a',function(){document.location.href=this.href;});
	mui('.comment').on('tap','a',function(){document.location.href=this.href;});

	mui('footer').on('tap','a',function(){document.location.href=this.href;});

	mui.init({
		swipeBack:false //启用右滑关闭功能
	});

	mui.previewImage();
	// var slider = mui("#slider");
	// slider.slider({
	// 	interval: 3000
	// });

	//判断是否微信登陆
    function isWeiXin() {
        var ua = window.navigator.userAgent.toLowerCase();
        console.log(ua);//mozilla/5.0 (iphone; cpu iphone os 9_1 like mac os x) applewebkit/601.1.46 (khtml, like gecko)version/9.0 mobile/13b143 safari/601.1
        if (ua.match(/MicroMessenger/i) == 'micromessenger') {
            return true;
        } else {
            return false;
        }
    }

    $("#Share").on('tap',function(){
    	var _this = $(this);
    	if (isWeiXin()) {
        	layer.tips('点击右上角"…"即可分享~', _this, {tips: [3,"#393D49"], time:3000});
	    } else {
	        layer.msg("可以使用浏览器分享按钮<br>拷贝网址分享给好友哦",{time:3000});
	    }
    })
</script>
{% endblock %}
{% block footer %}
       {{ partial('common/footer_Db')}}
{% endblock %}