<footer>
	<a href="/mjob/main#tabbar" class="col-xs-4">
		<span class="icon-1 iconpng"></span>
		<span class="mui-tab-label">数据挖矿</span>
	</a>
	<a href="/mjob/main#tabbar" class="col-xs-4 active">
		<span class="icon-2 iconpng"></span>
		<span class="mui-tab-label">金职岛</span>
	</a>
	<a href="/mjob/main#tabbar" class="col-xs-4">
		<span class="icon-3 iconpng"></span>
		<span class="mui-tab-label">我的身份</span>
	</a>
</footer>
<script type="text/javascript">
	mui('footer').on('tap','a',function(){document.location.href=this.href;});
</script>