{% extends "common/mobile-index.phtml" %}
{% block title  %}金职夺宝 - 参与记录{% endblock %}
{% block css %}{{ stylesheetLink('css/db/db.css') }}{% endblock %}
{% block content %}
<style type="text/css">
	html,body {
		height: 100%;
	}
	.mui-table-view {
		margin-top: 0 !important;
		margin-bottom: 6.82rem;
	}
	.mui-table-view:before,
	.mui-table-view:after {
		background: transparent;
	}
	.mui-table-view-cell {
		height: 8.9rem;
		padding:15px;
	}
	.mui-table-view-cell .item {
		height: 100%;
		display: block;
		margin:0 !important;
		padding:0 !important;
		overflow: inherit !important;
		white-space: inherit !important;
	}
	.mui-table-view .mui-media-object {
		width: 6.46rem;
		max-width:6.46rem;
		height: 6.46rem;
	}
	.mui-table-view-cell:after {
		right: 15px;
	}
	.mui-table-view-cell .title {
		height: 3rem;
		/*margin-bottom: 1.4rem;*/
		color:#67686e;
		line-height: 1.58rem;
		font-size:1.14rem;
		overflow: hidden;
	}
	.mui-table-view-cell .title .tips {
		background: #fbb73c;
		display: inline-block;
		width: 5.5rem;
		height: 1.52rem;
		line-height: 1.58rem;
		color:#fff;
		text-align: center;
		margin-right: 5px;
		border-radius: 1.52rem;
	}
	.mui-table-view-cell .num {
		height: 1.4rem;
		line-height: 1.4rem;
		font-size:1rem;
		color:#67686e;
	}
	.mui-table-view-cell .num span {
		color:#ff2a63;
	}
	.mui-table-view-cell .status {
		height: 2.5rem;
		font-size: 1rem;
	}
	.mui-table-view-cell .status .rate,
	.mui-table-view-cell .status .link {
		padding:0;
	}
	.mui-table-view-cell .status .rate.col-xs-7 {
		width: 65%;
	}
	.mui-table-view-cell .status .rate p {
		font-size:1rem;
	}
	.mui-table-view-cell .status .rate .progressrow {
		width: 100%;
		height: 5px;
		background: #d7dae7;
		border-radius: 5px;
		position:relative;
	}
	.mui-table-view-cell .status .rate .progress {
		position: absolute;
		top:0;
		left:0;
		height: 5px;
		border-radius: 5px;
	}
	.mui-table-view-cell .status .link {
		height: 2.09rem;
		line-height: 2.09rem;
		border-radius: 2.09rem;
		text-align: center;
		font-size: 1.14rem;
		color:#fff;
	}
	.mui-table-view-cell .status .link.disabled {
		background: #d7dae7;
	}
	.winbox {
		position: absolute;
	    /*top: 5px;
	    left: 5px;
	    width: 4.5rem;
	    height: 4.5rem;*/
	    width: 3.8rem;
	    height: 1.27rem;
	    top:25px;
	    left:15px;
	    /*border-radius: 50%;
	    line-height: 4rem;
	    font-weight: 700;
	    text-align: center;
	    transform: rotate(-45deg);
	    -ms-transform: rotate(-45deg);
	    -moz-transform: rotate(-45deg);
	    -webkit-transform: rotate(-45deg);
	    -o-transform: rotate(-45deg);
	    opacity: 0.5;
	    font-family: "黑体";*/
	    z-index: 2; 
	}
	.winbox.nowin {
		/*border:5px solid #fbb73c;
		color:#fbb73c;
		font-size: 1.2rem;*/
		background: url("/public/img/db/nowin.png") center no-repeat;
		background-size: contain;
	}
	.winbox.win {
		/*border:5px solid #f00;
		color:#f00;
		font-size: 1.6rem;*/
		background: url("/public/img/db/win.png") center no-repeat;
		background-size: contain;
	}
	.statC button.link {
		position: relative;
		z-index:5;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">参与记录</h1>
</header>

<div class="mui-content">
	{% if data['listuser'] %}
		<ul class="mui-table-view">
			{% for key, item in data['listuser'] %}
				{% if item['is_end'] == 'N' %}
					<li class="mui-table-view-cell mui-media statA">
				{% else %}
					{% if item['is_win'] == 'N' %}
					<li class="mui-table-view-cell mui-media statB">
					<div class="winbox nowin"></div>
					{% else %}
					<li class="mui-table-view-cell mui-media statC">
					<div class="winbox win"></div>
					{% endif %}
				{% endif %}
					<a href="/db/detail/{{ item['list_id'] }}" class="item">
						<img class="mui-media-object mui-pull-left" src="{{ item['imgs'][0] }}">
						<div class="mui-media-body">
							<div class="title">
								<span class="tips">{{ item['no'] }}期</span>
								{{ item['pname'] }}
							</div>
							<div class="num">参与次数：<span>{{ item['count'] }}</span>次</div>
							<div class="status">
								<div class="rate col-xs-7">
									<p>夺宝进度：<span>{{ item['percent'] }}%</span></p>
									<div class="progressrow">
										<div class="progress gradual" style="width:{{ item['percent'] }}%"></div>
									</div>
								</div>
								{% if item['is_end'] == 'N' %}
									<button class="btn link col-xs-4 right gradual">查看</button>
								{% else %}
									{% if item['is_win'] == 'N' %}
										<button class="btn link col-xs-4 right gradual">查看</button>
									{% else %}
										{% if item['is_comment'] == 'N' %}
										<button class="link col-xs-4 right gradual" onclick="turn({{ item['list_id'] }})">晒单</button>
										{% else %}
										<button class="link col-xs-4 right gradual disabled">已晒单</button>
										{% endif %}
									{% endif %}
								{% endif %}

							</div>
						</div>
					</a>
				</li>
			{% endfor %}
		</ul>
	{% else %}
		<div class="noneshow">暂无参与记录。</div>
	{% endif %}
</div>
<script type="text/javascript">
	function turn(list_id){
		event.preventDefault();
		window.location.href = "/db/comment/"+list_id;
	}
</script>

{% endblock %}
{% block footer %}
       {{ partial('common/footer_Db')}}
{% endblock %}
