{% extends "common/mobile-index.phtml" %}
{% block title  %}金职夺宝 - 系统消息{% endblock %}
{% block css %}{{ stylesheetLink('css/db/db.css') }}{% endblock %}
{% block content %}
<style type="text/css">
	html,body {
		height: 100%;
		background-color: #efeff4;
	}
	
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">系统消息</h1>
</header>

<div class="mui-content">
	<div class="noneshow">
		暂无系统消息。
	</div>
</div>


{% endblock %}
{% block footer %}
       {{ partial('common/footer_Db')}}
{% endblock %}