{% extends "common/mobile-index.phtml" %}
{% block title  %}金职夺宝 - 系统消息{% endblock %}
{% block css %}{{ stylesheetLink('css/db/db.css') }}{% endblock %}
{% block content %}
<style type="text/css">
	html,body {
		height: 100%;
		background-color: #efeff4;
	}
	.mui-bar-nav~.mui-content {
		padding-bottom: 5.82rem;
	}
	h2 {
		margin:0;
		margin-top:10px;
		margin-bottom: 5px;
		color:#c6cacf;
		font-size:1rem;
		text-align: center;
	}
	.mui-card h4 {
		color:#434347;
		font-size:1.8rem;
	}
	.mui-card p {
		color:#a4a6ad;
		font-size:1rem;
	}
	.mui-card-footer a {
		display: block;
		width: 100%;
		text-align: center;
		font-size:1.4rem;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">系统消息</h1>
</header>

{% if data['sysnotice'] %}
	<div class="mui-content">
		{% for key, item in data['sysnotice'] %}
		<h2>{{  item['create_time'] }}</h2>
		<div class="mui-card">
			<div class="mui-card-content">
				<div class="mui-card-content-inner">
					{% if item['type'] == 'coingetwin' %}
						<h4>中奖公告</h4>
					{% else %}
						<h4>其它</h4>
					{% endif %}
					<p>{{item['content']}}</p>
				</div>
			</div>
			<div class="mui-card-footer">
				<a href="{{ item['url'] }}" class="link">查看详情</a>
			</div>
		</div>
		{% endfor %}
	</div>
{% else %}
	<div class="mui-content">
		<img src="/public/img/db/noneshow.png" class="nonepng">
		<div class="noneshow">
			暂无系统消息。
		</div>
	</div>
{% endif %}


{% endblock %}
{% block footer %}
       {{ partial('common/footer_Db')}}
{% endblock %}