{% extends "common/mobile-index.phtml" %}
{% block title  %}金职夺宝 - 系统消息{% endblock %}
{% block css %}{{ stylesheetLink('css/db/db.css') }}{% endblock %}
{% block content %}
<style type="text/css">
	html,body {
		height: 100%;
		background-color: #efeff4;
	}
	.mui-bar-nav~.mui-content {
		padding-bottom: 5.82rem;
	}
	h2 {
		margin:0;
		margin-top:10px;
		margin-bottom: 5px;
		color:#c6cacf;
		font-size:1rem;
		text-align: center;
	}
	.mui-card h4 {
		color:#434347;
		font-size:1.8rem;
	}
	.mui-card p {
		color:#a4a6ad;
		font-size:1rem;
	}
	.mui-card-footer a {
		display: block;
		width: 100%;
		text-align: center;
		font-size:1.4rem;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">系统消息</h1>
</header>

<div class="mui-content none">
	<img src="/public/img/db/noneshow.png" class="nonepng">
	<div class="noneshow">
		暂无系统消息。
	</div>
</div>

<div class="mui-content">
	<h2>2018-07-21</h2>
	<div class="mui-card">
		<div class="mui-card-content">
			<div class="mui-card-content-inner">
				<h4>JOB奖励发放</h4>
				<p>这里显示文章摘要，让读者对文章内容有个粗略的概念...</p>
			</div>
		</div>
		<div class="mui-card-footer">
			<a href="/db/index" class="link">查看详情</a>
		</div>
	</div>
	<h2>2018-07-21</h2>
	<div class="mui-card">
		<div class="mui-card-content">
			<div class="mui-card-content-inner">
				<h4>JOB奖励发放</h4>
				<p>这里显示文章摘要，让读者对文章内容有个粗略的概念...</p>
			</div>
		</div>
		<div class="mui-card-footer">
			<a href="/db/index" class="link">查看详情</a>
		</div>
	</div>
	<h2>2018-07-21</h2>
	<div class="mui-card">
		<div class="mui-card-content">
			<div class="mui-card-content-inner">
				<h4>JOB奖励发放</h4>
				<p>这里显示文章摘要，让读者对文章内容有个粗略的概念...</p>
			</div>
		</div>
		<div class="mui-card-footer">
			<a href="/db/index" class="link">查看详情</a>
		</div>
	</div>
</div>


{% endblock %}
{% block footer %}
       {{ partial('common/footer_Db')}}
{% endblock %}