{% extends "common/mobile-index.phtml" %}
{% block title  %}金职夺宝 - 购买成功{% endblock %}
{% block css %}{{ stylesheetLink('css/db/db.css') }}{% endblock %}
{% block content %}
<style type="text/css">
	html,body {
		height: 100%;
	}
	.box {
		width: 40%;
		margin:0 auto;
		margin-top:5.06rem;
	}
	.box img {
		width: 100%;
		display: block;
	}
	p {
		color:#67686e;
		text-align: center;
		font-size:1.5rem;
		margin-top:2.4rem;
		margin-bottom: 4.8rem;
	}
	p span {
		color:#f87729;
		display: inline-block;
		margin:0 3px;
	}
	.mui-content {
		padding-bottom: 15rem !important;
	}
	.mui-content a {
		width: 50%;
		margin:0 auto;
		display: block;
		font-size: 1.14rem !important;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">购买成功</h1>
</header>

<div class="mui-content">
	<div class="box">
		<img src="/public/img/db/success.png">
	</div>
	<p>成功参与<span></span>人次</p>
	<a href="/db/joinrecord" class="btn btn-default btn-lg" role="button">查看参与记录</a>
</div>
<script type="text/javascript">
	$(function(){
		var urlArr = window.location.href.split('=');
	    var num = urlArr[1];
	    $('p span').html(num);
	});
</script>

{% endblock %}
{% block footer %}
       {{ partial('common/footer_Db')}}
{% endblock %}
