{% extends "common/mobile-index.phtml" %}
{% block title  %}金职夺宝 - 玩家晒单{% endblock %}
{% block css %}{{ stylesheetLink('css/db/db.css') }}{% endblock %}
{% block content %}
<style type="text/css">
	body,html,.mui-content {
		background: #fff;
		overflow: none;
		/*padding:0;*/
	}
	.mui-content {
		overflow: auto;
		margin-bottom: -22px;
		padding-bottom: 24px;
	}
	/*html {
		padding-bottom: 5.82rem;
	}*/
	.comment {
		position: relative;
		overflow: hidden;
		/*margin-bottom: 10px;*/
	}
	.comment::after {
		content: "";
		background: #eee;
		width: 110%;
	    height: 10px;
	    margin-left: -15px;
	    margin-right: -15px;
	    position: absolute;
	    left: 0;
	    bottom: -5px;
	    display: block;
	}
	.comment .userinfo {
		margin:.8rem 0;
		height: 2.85rem;
		line-height: 2.85rem;
		color:#67686e;
		font-size:1.14rem;
	}
	.comment .userinfo .user img {
		width: 2.85rem;
		height: 2.85rem;
		border-radius: 50%;
		margin-right: .5rem;
		display: inline-block;
	}
	.comment .userinfo .time {
		color:#a4a6ad;
	}
	.comment .userinfo .user .username {
	    width: 2.85rem;
	    height: 2.85rem;
	    border-radius: 50%;
	    margin-right: .5rem;
	    display: inline-block;
	    text-align: center;
	    color: #fff;
	    font-family: "黑体";
	    background: #fbb73c;
	    font-size: 2rem;
	    float: left;
	}
	.comment p {
		font-size: 1rem;
		color:#67686e;
		line-height: 1.8rem;
		width: 100%;
	    height: auto;
	    word-wrap: break-word;
	    word-break: break-all;
	    overflow: hidden;
	}
	.comment .picturerow {
		width: 107%;
	}
	.comment .picturerow .rel {
		height:6rem;
		width: 20%;
		margin-right: 4%;
		margin-bottom: 10px;
		padding:2px;
		border:1px solid #eee;
		float:left;
	}
	.comment .picturerow .rel img {
		max-width: 98%;
		max-height: 98%;
	}
	.comment hr {
		margin-top:0;
		margin-bottom: 5px;
	}
	.comment .itemlink {
		color:#a4a6ad;
		font-size: 1rem;
		display: block;
		text-decoration: none;
		padding-bottom: 1rem;
	}
	.mui-pull-bottom-pocket  {
		position: absolute;
		bottom: -28px;
	}
</style>
<style type="text/css">
	.mui-preview-image.mui-fullscreen {
		position: fixed;
		z-index: 20;
		background-color: #000;
	}
	.mui-preview-header,
	.mui-preview-footer {
		position: absolute;
		width: 100%;
		left: 0;
		z-index: 10;
	}
	.mui-preview-header {
		height: 44px;
		top: 0;
	}
	.mui-preview-footer {
		height: 50px;
		bottom: 0px;
	}
	.mui-preview-header .mui-preview-indicator {
		display: block;
		line-height: 25px;
		color: #fff;
		text-align: center;
		margin: 15px auto 4;
		width: 70px;
		background-color: rgba(0, 0, 0, 0.4);
		border-radius: 12px;
		font-size: 16px;
	}
	.mui-preview-image {
		display: none;
		-webkit-animation-duration: 0.5s;
		animation-duration: 0.5s;
		-webkit-animation-fill-mode: both;
		animation-fill-mode: both;
	}
	.mui-preview-image.mui-preview-in {
		-webkit-animation-name: fadeIn;
		animation-name: fadeIn;
	}
	.mui-preview-image.mui-preview-out {
		background: none;
		-webkit-animation-name: fadeOut;
		animation-name: fadeOut;
	}
	.mui-preview-image.mui-preview-out .mui-preview-header,
	.mui-preview-image.mui-preview-out .mui-preview-footer {
		display: none;
	}
	.mui-zoom-scroller {
		position: absolute;
		display: -webkit-box;
		display: -webkit-flex;
		display: flex;
		-webkit-box-align: center;
		-webkit-align-items: center;
		align-items: center;
		-webkit-box-pack: center;
		-webkit-justify-content: center;
		justify-content: center;
		left: 0;
		right: 0;
		bottom: 0;
		top: 0;
		width: 100%;
		height: 100%;
		margin: 0;
		-webkit-backface-visibility: hidden;
	}
	.mui-zoom {
		-webkit-transform-style: preserve-3d;
		transform-style: preserve-3d;
	}
	.mui-slider .mui-slider-group .mui-slider-item img {
		width: auto;
		height: auto;
		max-width: 100%;
		max-height: 100%;
	}
	.mui-android-4-1 .mui-slider .mui-slider-group .mui-slider-item img {
		width: 100%;
	}
	.mui-android-4-1 .mui-slider.mui-preview-image .mui-slider-group .mui-slider-item {
		display: inline-table;
	}
	.mui-android-4-1 .mui-slider.mui-preview-image .mui-zoom-scroller img {
		display: table-cell;
		vertical-align: middle;
	}
	.mui-preview-loading {
		position: absolute;
		width: 100%;
		height: 100%;
		top: 0;
		left: 0;
		display: none;
	}
	.mui-preview-loading.mui-active {
		display: block;
	}
	.mui-preview-loading .mui-spinner-white {
		position: absolute;
		top: 50%;
		left: 50%;
		margin-left: -25px;
		margin-top: -25px;
		height: 50px;
		width: 50px;
	}
	.mui-preview-image img.mui-transitioning {
		-webkit-transition: -webkit-transform 0.5s ease, opacity 0.5s ease;
		transition: transform 0.5s ease, opacity 0.5s ease;
	}
	@-webkit-keyframes fadeIn {
		0% {
			opacity: 0;
		}
		100% {
			opacity: 1;
		}
	}
	@keyframes fadeIn {
		0% {
			opacity: 0;
		}
		100% {
			opacity: 1;
		}
	}
	@-webkit-keyframes fadeOut {
		0% {
			opacity: 1;
		}
		100% {
			opacity: 0;
		}
	}
	@keyframes fadeOut {
		0% {
			opacity: 1;
		}
		100% {
			opacity: 0;
		}
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">玩家晒单</h1>
</header>

<div id="pullrefresh" class="mui-content mui-scroll-wrapper">
	<div class="container mui-scroll">
		{% if data['listusercomment'] %}
			{% for key, item in data['listusercomment'] %}
				<div class="comment">
					<div class="userinfo">
						<div class="user left">
							<span class="username">{{ item['username'] }}</span>{{ item['phone'] }}
						</div>
						<div class="time right">{{ item['create_time'] }}</div>
					</div>
					<p>
						{{ item['comment'] }}
					</p>
					<div class="picturerow">
						{% for key2, item2 in item['imgs'] %}
							<div class="rel">
								<img src="{{ item2 }}" class="auto-center" data-preview-src=""  data-preview-group="{{key}}">
							</div>
						{% endfor %}
						<div class="cls"></div>
					</div>
					<hr>
					<a href="/db/detail/{{ item['list_id'] }}" class="itemlink">{{ item['pname'] }}</a>
				</div>
			{% endfor %}
		{% else %}
			<img src="/public/img/db/noneshow.png" class="nonepng">
			<div class="noneshow">暂无用户晒单。</div>
		{% endif %}
	</div>
</div>

<script src="/public/js/db/mui.zoom.js"></script>
<script src="/public/js/db/mui.previewimage.js"></script>
<script type="text/javascript">

	$(function(){
		$('span.username').each(function(){
			var text = $(this).text();
			if(text != ''){
				$(this).html(text.substring(0,1));
			} else {
				$(this).html('无');
			}
		});
	});

	mui.init({
		// swipeBack:true, //启用右滑关闭功能
		// pullRefresh: {
		// 	container: '#pullrefresh',
		// 	up: {
		// 		auto:false,
		// 		contentrefresh: '正在加载...',
		// 		callback: pullupRefresh
		// 	}
		// }
	});

	// var count = 0;
	// function pullupRefresh() {
	// 	setTimeout(function() {
	// 		mui('#pullrefresh').pullRefresh().endPullupToRefresh((++count > 3)); //参数为true代表没有更多数据了。
	// 		// var table = document.body.querySelector('.container');
	// 		// var cells = document.body.querySelectorAll('.comment');
	// 		var table = $(".container");
	// 		var cells = $('.comment');
	// 		var newCount = cells.length > 0 ? 5 : 20;//首次加载20条，满屏
	// 		for (var i = cells.length, len = i + newCount; i < len; i++) {
	// 			var dom = "<div class='comment'>"
	// 					+	"<div class='userinfo'>"
	// 					+		"<div class='user left'>"
	// 					+			"<img src='/public/img/db/1.jpg'>香蕉你个巴拉"
	// 					+		"</div>"
	// 					+		"<div class='time right'>2018/02/08</div>"
	// 					+	"</div>"
	// 					+	"<p>"+'asdsadasdsadasdsadsajadiojioasjdiosajdoisajoidjsoaijdo'+"</p>"
	// 					+	"<div class='picturerow'>"
	// 					+		"<div class='rel'>"
	// 					+			"<img src='/public/img/db/1.jpg' class='auto-center' data-preview-src=''  data-preview-group='"+i+"'>"
	// 					+		"</div>"
	// 					+		"<div class='rel'>"
	// 					+			"<img src='/public/img/db/1.jpg' class='auto-center' data-preview-src=''  data-preview-group='"+i+"'>"
	// 					+		"</div>"
	// 					+		"<div class='rel'>"
	// 					+			"<img src='/public/img/db/1.jpg' class='auto-center' data-preview-src=''  data-preview-group='"+i+"'>"
	// 					+		"</div>"
	// 					+		"<div class='rel'>"
	// 					+			"<img src='/public/img/db/1.jpg' class='auto-center' data-preview-src=''  data-preview-group='"+i+"'>"
	// 					+		"</div>"
	// 					+		"<div class='rel'>"
	// 					+			"<img src='/public/img/db/1.jpg' class='auto-center' data-preview-src=''  data-preview-group='"+i+"'>"
	// 					+		"</div>"
	// 					+		"<div class='cls'></div>"
	// 					+	"</div>"
	// 					+	"<hr>"
	// 					+	"<a href='#' class='itemlink'>iPhone X 64G 深空灰 三网通 支持JOB币资产购买</a>"
	// 					+ "</div>";
	// 			table.append(dom);
	// 		}
	// 	}, 1500);
	// }
	
	mui.previewImage();

	mui('.comment').on('tap','a',function(){document.location.href=this.href;});
</script>
{% endblock %}
{% block footer %}
       {{ partial('common/footer_Db')}}
{% endblock %}