{% extends "common/mobile-index.phtml" %}
{% block title  %}金职岛 - 关于金职链{% endblock %}


{% block content %}
<style type="text/css">
	body,html,.mui-content {
		height:100%;
	}
	div img {
		max-width: 100%;
		margin-top:-7rem;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">关于金职链</h1>
</header>


<div class="mui-content">
	<img src="/public/img/mjob/aboutus.png">
</div>


{% endblock %}