{% extends "common/mobile-index.phtml" %}
{% block title  %}金职岛 - 我的资产{% endblock %}

{% block content %}
<style type="text/css">
	body,html,.mui-content {
		height:100%;
	}
	.banner {
		height: 8.35rem;
		position: relative;
		background: #1f36bf url("/public/img/mjob/recordbanner.png") no-repeat center;
		background-size: 74%;
	}
	.banner > div {
		font-size:3rem;
		color:#fac82e;
		text-align: center;
		width: 100%;
		height: 4.74rem;
	}
	.banner div span {
		display: inline-block;
		position: absolute;
		top:0;
		left:0;
		bottom: 0;
		right:0;
		margin:auto;
		top: 3.5rem;
		width: 8.35rem;
		height: 1.3rem;
		font-size:1rem;
		color:#aab6ff;
	}
	h3 {
		margin-top: 1.85rem;
		font-size:1.33rem;
		text-align: left;
		color:#65676e;
		font-weight: 700;
	}
	div.line {
		background: #fac82e;
		width: 10%;
		height: .3rem;
		/*margin:0 auto;*/
	}
	p {
		margin-top:1.45rem;
		font-size:1.14rem;
		color:#98999e;
		line-height: 1.8rem;
	}
	hr {
		border-top: 1px solid #cbcbcb;
		margin-top: 10px;
	}
	.mui-btn-block {
	    height: 4.62rem;
	    border-radius: 4.62rem;
	    font-size: 1.6rem;
	    width: 80%;
	    margin: 0 auto;
	    border: 1px solid #1de291;
	    background-color: #1de291;
	    margin-top: 1rem;
	    margin-bottom: 5rem;
	}
</style>


<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">我的资产</h1>
	<a class="mui-pull-right" href="iae">收支记录</a>
</header>

<div class="mui-content">
	<div class="banner">
		<div class="auto-center">{{ data['jobcoin'] }}<span>JOB币总数</span></div>
	</div>
	<div class="container">
		<h3>JOB币简介</h3>
		<div class="line"></div>
		<p>job币是新加坡金职基金会在JOBChain（金职链）上发行的Token，不仅具有流通价值，同时在金职链上开发、认证应用、使用链上服务（例如链上转账的旷工费）等需要支付或燃烧job币，job币是作为链上应用运行唯一使用到的Token。在金职岛中也可以很方便地利用job币进行支付结算，如岛上居民之间互相使用job币进行结算，使用岛上公共服务需要用job币结算，商家提供的服务也需要job币来购买等等。</p>
		<hr>
		<a href="/mjob/buyorder" class="mui-btn mui-btn-block mui-btn-success">充值</a>
	</div>
</div>


{% endblock %}