{% extends "common/mobile-index.phtml" %}
{% block title  %}金职岛 - 购买JOB币{% endblock %}


{% block content %}
<style type="text/css">
	body,html,.mui-content {
		height:100%;
	}
	.mui-content {
		background: #fff;
	}
	div img {
		max-width: 100%;
	}
	p {
		font-size:1rem;
	}
	.mui-input-group {
		background: transparent;
	}
	.mui-input-row p {
		height: 40px;
		padding: 10px 15px;
		line-height: 21px;
		float: right;
	    width: 65%;
	    margin: 0;
	    padding-left: 0;
	    border: 0;
	    color:#67686e !important;
	}
	.mui-btn-block {
	    height: 4.62rem;
	    border-radius: 4.62rem;
	    font-size: 1.6rem;
	    width: 80%;
	    margin: 0 auto;
	    border: 1px solid #1de291;
	    background-color: #1de291;
	    margin-top: 1rem;
	    margin-bottom: 4rem;
	}
	#Waiting {
		padding:20px;
		width: 100%;
		overflow: hidden;
		text-align: center;
		color:#67686e;
	}
	#Waiting p {
		font-size:1.14rem;
		color:#67686e;
		margin-bottom: 1rem;
	}
	#marquee {
		width: 30rem;
		height: 4rem;
		position: relative;
		overflow: hidden;
	}
	#marquee .head {
		width: 4rem;
		height: 4rem;
		border-radius: 50%;
		margin-right: 1rem;
		overflow: hidden;
		position: relative;
		float:left;
	}
	span.import {
		color:#ff2a63;
	}
	#Tip h2 {
		background: #ff2f5e;
	    color: #fff;
	    text-align: center;
	    margin: 0;
	    margin-bottom: 1rem;
	    border: 5px solid #FFF;
	    height: 3.78rem;
	    font-size: 2rem;
	    line-height: 3rem;
	    padding: 0;
	}
	#Tip h2 span {
		display: inline-block;
	    width: 1.4rem;
	    height: 1.4rem;
	    border-radius: 50%;
	    color: #ff2a63;
	    background: #fff;
	    line-height: 1.7rem;
	    text-align: center;
	    margin-right: 5px;
	    font-size: 1rem;
	}
	#Tip p {
		color:#67686e;
		margin-bottom: 5px;
	}
	#Tip button {

	}
	#Next {
		width: 10rem;
		display: block;
		margin:0 auto;
		margin-bottom: 2rem;
	}
	#Info h6 {
		text-align: center;
		margin: .8rem 0;
	}
	#Info h6,
	#Info .col-xs-4,
	#Info .col-xs-5 {
		color:#a4a6ad;
	}
	#Info .col-xs-4,
	#Info .col-xs-5 {
		text-align: right;
	}
	#Info .col-xs-8,
	#Info .col-xs-7 {
		padding-left: 0;
	}
	#Info .col-xs-8,
	#Info .col-xs-7
	#Info p {
		color:#67686e;
	}
	#Info p {
		margin-bottom: 5px !important;
	}
	#Info .infobox {
		border:1px solid #eee;
		background: #f4f5f9;
		padding:10px;
		margin-bottom: 1rem;
	}
	#Info .infobox .infos {
		margin-bottom: 1rem;
		font-size:1rem;
	}
	#Info .row {
		margin-bottom: 5px;
	}
	#Info .col-xs-2 {
		height: 0;
		padding:8%;
	}
	#Info .col-xs-10 {
		background: #e6e9fb;
		padding:10px;
		float:right;
	}
	.statusbox {
		height: 7rem;
		margin-top:2.6rem;
		margin-bottom: 2rem;
	}
	#statA h2 {
		text-align: center;
		font-size: 1.52rem;
		color:#67686e;
		margin: 3rem 0;
	}
	#statA h2::after {
		content: '';
		display: block;
		width: 10%;
	    height: 5px;
	    margin: 0 auto;
	    margin-top: 5px;
	    background: #67686e;
	}
	.mui-input-group:before,
	.mui-input-group .mui-input-row:after,
	.mui-input-group:after {
		background: transparent;
	}
	.mui-input-row .mui-input-clear~.mui-icon-clear {
		top:7px;
		right:5%;
	}
	.mui-radio {
		width: 33%;
	    float: left;
	    clear:none;
	    height: 3.2rem;
	}
	.mui-radio label {
	    width: 100%;
	    padding: 0;
	    height: 3rem;
	    line-height: 3.5rem;
	    text-align: left;
	    font-size: 1.5rem;
	    padding:0 !important;
	    padding-left: 2rem !important;
	}
	.mui-radio.raidoactive label {
		color:#007aff;
	}
	.mui-radio label span {
		position: relative;
		top:0px;
		left: -5px;
		font-size: 1.5rem;
	}
	.mui-radio.mui-left input[type=radio] {
		left:-10px;
		top: 0;
		width: 3rem;
    	height: 3rem;
	}
	.mui-checkbox input[type=checkbox]:before, .mui-radio input[type=radio]:before {
		font-size:3rem;
		content:'\e472';
	}
	.mui-checkbox input[type=checkbox]:checked:before, .mui-radio input[type=radio]:checked:before {
		content: '\e472';
		color: #007aff;
	}
	#statA p {
		margin-bottom: 5px;
		color:#ff2a63;
	}
	#statA input[type=text],
	#statA input[type=tel], {
		height:35px;
		padding:5px 10px;
		border:1px solid #eee;
		text-align: center;
		float: left;
    	width: 60%;
	}
	#statA label {
		font-weight:300;
	}
	#statA input[disabled] {
		background: #eee !important;
	}
	#statA p.tips span {
		display: inline-block;
		width: 1.4rem;
	    height: 1.4rem;
	    border-radius: 50%;
	    color: #fff;
	    background: #ff2a63;
	    line-height: 1.5rem;
	    text-align: center;
	    margin-right: 1px;
	}
	#statA .fill {
		margin-top:1rem;
	}
	#statA .fill label {
		text-align: center;
	}
	#statB .headbox {
		height: 8rem;
		width: 8rem;
		margin:0 auto;
		border-radius: 50%;
		overflow:hidden;
		position: relative;
		margin-bottom: 1rem;
		margin-top: 4rem;
	}
	#statB p,
	#statB a {
		text-align: center;
	}
	#statB a {
		width: 100%;
		display: block;
		text-decoration: underline;
		margin-top: 2rem;
	}
	h5 {
		text-align: center;
	    font-size: 1rem;
	    position: fixed;
	    bottom: 5%;
	    width: 93%;
	    color:#a4a6ad;
	}
	#loading{
		height: 5rem;
		width: 100%;
	}
	#loading-center{
		width: 100%;
		height: 100%;
		position: relative;
	}
	#loading-center-absolute {
	    height: 30px;
	    width: 90px;
	}
	.object {
		width: 4px;
		height: 25px;
		margin-right:5px;
		background-color: #67686e;
		-webkit-animation: animate 1s infinite;
		animation: animate 1s infinite;
		float: left;
	}
	.object:last-child {
		margin-right: 0px;
		}

	.object:nth-child(10){
		-webkit-animation-delay: 0.9s;
	    animation-delay: 0.9s;	
		}
	.object:nth-child(9){
		-webkit-animation-delay: 0.8s;
	    animation-delay: 0.8s;	
		}	
	.object:nth-child(8){
		-webkit-animation-delay: 0.7s;
	    animation-delay: 0.7s;	
		}
	.object:nth-child(7){
		-webkit-animation-delay: 0.6s;
	    animation-delay: 0.6s;	
		}
	.object:nth-child(6){
		-webkit-animation-delay: 0.5s;
	    animation-delay: 0.5s;	
		}
	.object:nth-child(5){
		-webkit-animation-delay: 0.4s;
	    animation-delay: 0.4s;
		}
	.object:nth-child(4){
		-webkit-animation-delay: 0.3s;
	    animation-delay: 0.3s;		
		}
	.object:nth-child(3){
		-webkit-animation-delay: 0.2s;
	    animation-delay: 0.2s;	
		}
	.object:nth-child(2){
		-webkit-animation-delay: 0.1s;
	    animation-delay: 0.1s;
		}

	@-webkit-keyframes animate {
	  50% {
		-ms-transform: scaleY(0); 
	   	-webkit-transform: scaleY(0);
	    transform: scaleY(0);
		  }
	}
	@keyframes animate {
	  50% {
		-ms-transform: scaleY(0); 
	   	-webkit-transform: scaleY(0);
	    transform: scaleY(0);
		  }
	}
	#QRcode {
		height:6rem;
		margin:1rem auto;
		position: relative;
	}
	#QRcode .col-xs-5,
	#QRcode .col-xs-7 {
		height: 100%;
		line-height: 6rem;
		font-size:1rem;
	}
	#QRcode .col-xs-7 {
		width: 6rem;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">购买JOB币</h1>
	<a class="mui-pull-right" href="orders">订单记录</a>
</header>


<div class="mui-content">
	<div class="container">
		<div id="statA">
			<div class="statusbox rel">
				<img src="/public/img/mjob/stat1.png" class="auto-center">
			</div>
			<h2>请填写委托购买订单</h2>
			<p>*JOB充提代理当前时刻汇率：1 JOB = 0.1 元</p>
			<p>*如果你有3笔未完成的买单,系统会暂停你的下单权限,完成后恢复</p>
			<h4>请选择支付方式：</h4>
			<div class="choose">
				<div class="mui-input-row mui-radio mui-left raidoactive">
					<label><span class="mui-icon mui-icon-weixin"></span>微信</label>
					<input name="pay" type="radio" data-model="C" checked>
				</div>
				<div class="mui-input-row mui-radio mui-left">
					<label><span class="mui-icon-extra mui-icon-extra-alipay"></span>支付宝</label>
					<input name="pay" type="radio" data-model="B">
				</div>
				<div class="mui-input-row mui-radio mui-left">
					<label><span class="mui-icon-extra mui-icon-extra-card"></span>银联</label>
					<input name="pay" type="radio" data-model="A">
				</div>
				<div class='cls'></div>
			</div>
			<div class="row fill">
				<form class="mui-input-group">
					<!-- <div class="mui-input-row">
						<label>金职岛ID</label>
						<input type="text" class="mui-input-clear" placeholder="请填写买家ID" value="{{ userinfo['id'] }}" disabled id="userid">
					</div> -->
					<div id="modelC" class=" modelchange">
						<div class="mui-input-row">
							<label>微信昵称</label>
							<input type="text" class="mui-input-clear" placeholder="请填写微信昵称" id="wechatname" value="{{ userinfo['name'] }}">
						</div>
					</div>
					<div id="modelB" class="none modelchange">
						<div class="mui-input-row">
							<label>支付宝昵称</label>
							<input type="text" class="mui-input-clear" placeholder="请填写支付宝昵称" id="alipayname" value="{{ userinfo['name'] }}">
						</div>
					</div>
					<div id="modelA" class="modelchange none">
						<div class="mui-input-row">
							<label>开户人</label>
							<input type="text" class="mui-input-clear" placeholder="请填写姓名" id="username" value="{{ userinfo['name'] }}">
						</div>
						<div class="mui-input-row">
							<label>付款账号</label>
							<input type="text" class="mui-input-clear" placeholder="请输入付款银行账号" id="banknum" value="{{ data.bank_no }}">
						</div>
						<div class="mui-input-row">
							<label>付款银行</label>
							<input type="text" class="mui-input-clear" placeholder="请输入付款银行名称" id="bankname" value="{{ data.bank_name }}">
						</div>
					</div>
					<div class="mui-input-row">
						<label>购买金额</label>
						<input type="tel" class="mui-input-clear" placeholder="请填写要购买的金额" value="100" id="money">
					</div>
					<div class="mui-input-row">
						<label>（CNY）</label>
						<p>= <span id="JOBnum" class="import">1000</span> JOB</p>
					</div>
				</form>
			</div>
			<p class="tips none"><span>!</span> 单笔最少需充值5元。</p>
			<a href="javascript:void(0);" class="mui-btn mui-btn-block gradual" id="Buy">立即购买</a>
		</div>
		<div id="statB" class="none">
			<div class="statusbox rel">
				<img src="/public/img/mjob/stat2.png" class="auto-center">
			</div>
			<div class="headbox">
				<img src="/public/img/mjob/head1.png" class="auto-center">
			</div>
			<p style="font-size:1.5rem;">代理商<span class="import agent"></span>正在处理中，请稍后</p>
			<p>正常情况1小时内处理完毕</p>
			<p>遇到订单高峰期，处理时间相应延长</p>
			<a href="javascript:void(0)" id="showAgent">显示代理商收款账号信息</a>
			<h5>对订单有疑问，请加代理商QQ联系 <span id="qq"></span></h5>
		</div>
	</div>
</div>

<div id="Waiting" class="none">
	<div id="loading">
		<div id="loading-center">
			<div id="loading-center-absolute" class="auto-center">
				<div class="object"></div>
				<div class="object"></div>
				<div class="object"></div>
				<div class="object"></div>
				<div class="object"></div>
				<div class="object"></div>
				<div class="object"></div>
				<div class="object"></div>
				<div class="object"></div>
				<div class="object"></div>
			</div>
		</div>
	</div>
	<p>正在为您分配代理商，请稍后...</p>
	<hr>
	<div id="marquee">
		<div class="head"><img src="/public/img/mjob/head1.png" class="auto-center"></div>
		<div class="head"><img src="/public/img/mjob/head2.png" class="auto-center"></div>
		<div class="head"><img src="/public/img/mjob/head3.png" class="auto-center"></div>
		<div class="head"><img src="/public/img/mjob/head4.png" class="auto-center"></div>
		<div class="head"><img src="/public/img/mjob/head5.png" class="auto-center"></div>
		<div class="head"><img src="/public/img/mjob/head6.png" class="auto-center"></div>
		<div class="head"><img src="/public/img/mjob/head7.png" class="auto-center"></div>
		<div class="head"><img src="/public/img/mjob/head8.png" class="auto-center"></div>
	</div>
</div>

<div id="Tip" class="none">
	<h2><span>!</span>重要提示</h2>
	<div class="container">
		<p>1、务必按指定的金额<span class="import paynum">0</span>元转账</p>
		<p>小数点后随机增加的金额是您该笔转账的专属凭证，且会与整数部分一同充入您的账户，不按此金额转账将在5个工作日内退款</p>
		<p>2、务必在内<span class="import">30分钟</span>转账，否则将影响订单处理速度</p>
		<p>3、转账时<span class="import">无需备注任何信息</span>，否则将会被代理商退回，无法完成充值</p>
		<p class="payofbank none">4、请使用已在前一页面填写的本人银行卡转账(支持网上银行,手机银行)，<span class="import">禁止使用银联APP、ATM、POS机等第三方支付平台转账，否则将一律退回！！！</span></p>
		<hr>
		<button type="button" id="Next" class="mui-btn mui-btn-outlined">我知道了</button>
	</div>
</div>

<div id="Info" class="none">
	<div class="container">	
		<div style="margin-top:10px;">
			<div class="col-xs-2 rel">
				<img src="/public/img/mjob/head1.png" class="auto-center">
			</div>
			<div class="col-xs-10">
				<p>您好，我是金职岛认证代理商<span class="agent"></span></p>
				<p>本次由我为您服务！</p>
				<p>请按要求转账至以下账户</p>
				<p>收到转账后，我会尽快为您充入JOB</p>
			</div>
			<div class="cls"></div>
		</div>
		<h6>请在 <span id="time" class="import">00:30:00</span> 内完成转账</h6>
		<div class="infobox">
				<div class="infos">
					<div id="wechatpay" class=' paytype'>
						<div class="row">
							<div class="col-xs-5">支付方式</div>
							<div class="col-xs-7">微信转账</div>
						</div>
						<div class="row">
							<div class="col-xs-5">微信昵称</div>
							<div class="col-xs-7" id="wechatName"></div>
						</div>
					</div>
					<div id="alipay" class='none paytype'>
						<div class="row">
							<div class="col-xs-5">支付方式</div>
							<div class="col-xs-7">支付宝转账</div>
						</div>
						<div class="row">
							<div class="col-xs-5">支付宝昵称</div>
							<div class="col-xs-7" id="alipayName"></div>
						</div>
					</div>
					<div id="bankpay" class="paytype none">
						<div class="row">
							<div class="col-xs-4">支付方式</div>
							<div class="col-xs-8">银行转账</div>
						</div>
						<div class="row">
							<div class="col-xs-4">开户名</div>
							<div class="col-xs-8" id="agentName"></div>
						</div>
						<div class="row">
							<div class="col-xs-4">账户名称</div>
							<div class="col-xs-8" id="agentBank"></div>
						</div>
						<div class="row">
							<div class="col-xs-4">银行卡号</div>
							<div class="col-xs-8" id="agentBankno"></div>
						</div>
					</div>
					<div class="row">
						<!-- <div class="col-xs-4"></div> -->
						<div class="col-xs-12" style="text-align:center;font-size:1rem;margin-top:1rem;">金额 <span class="import paynum">0</span> 元</div>
					</div>
					<div id="QRcode" class=''>
						<div class="col-xs-5">支付二维码</div>
						<div class="col-xs-7 rel"><img src="/public/img/mjob/head4.png" class="auto-center"></div>
					</div>
				</div>
			
			<div id="alipay"></div>
			<p>1、务必<span class="import">按指定的金额</span>转账，否则将无法完成购买（小数点后随机增加的金额是您该笔转账的专属凭证，且会与整数部分一同充入您的账户）</p>
			<p>2、转账时<span class="import">无需备注任何信息</span>，否则将会被代理商退回，无法完成充值</p>
			<p class="payofbank none">3、请使用本人银行卡转账(支持网上银行,手机银行)，<span class="import">禁止使用银联APP、ATM、POS机等第三方支付平台转账，否则将一律退回！！！</span></p>
		</div>
	</div>
</div>

<script type="text/javascript" src="{{url('js/mjob/bank.js')}}"></script>
<script type="text/javascript">

	 function scroll(){
		 $("#marquee").animate({"marginLeft":"-5rem"},300,"linear",function(){
		     $("#marquee .head:eq(0)").appendTo($("#marquee"))
		     $("#marquee").css({"marginLeft":0})
		 })
	 }
    setInterval(scroll,1);

    var NowTime; 
    var EndTime;

    var indexA;
    var indexB;
	var indexC;

	var model = "C";

    function getRTime(){ 
  		var now = new Date();
		var time = now.getTime();

        var t = EndTime - time; 
        //var d=Math.floor(t/1000/60/60/24); 
        var h = Math.floor(t/1000/60/60%24); 
        if(h < 10){
        	h = "0"+h;
        }
        var m = Math.floor(t/1000/60%60); 
        if(m < 10){
        	m = "0"+m;
        }
        var s = Math.floor(t/1000%60); 
        if(s < 10){
        	s = "0"+s;
        }
         
        //document.getElementById("t_d").innerHTML = d + "天"; 
        document.getElementById("time").innerHTML = h + ":" + m + ":" + s; 
        //document.getElementById("t_m").innerHTML = m + "分"; 
        //document.getElementById("t_s").innerHTML = s + "秒"; 
    }

    function setTime(){
    	setInterval(getRTime,1000);
    }

    $("input[name='pay']").change(function(){
		var mo = $(this).attr('data-model');
		var par = $(this).parent();
		par.addClass('raidoactive');
		par.siblings().removeClass('raidoactive');
		if(mo == "A"){
			$("#modelA").show().siblings('.modelchange').hide();
			$("#bankpay").show().siblings('.paytype').hide();
			$("#QRcode").hide();
			$(".payofbank").show();
		}
		if(mo == "B"){
			$("#modelB").show().siblings('.modelchange').hide();
			$("#alipay").show().siblings('.paytype').hide();
			$("#QRcode").show();
			$(".payofbank").hide();
		}
		if(mo == "C"){
			$("#modelC").show().siblings('.modelchange').hide();
			$("#wechatpay").show().siblings('.paytype').hide();
			$("#QRcode").show();
			$(".payofbank").hide();
		}
		model = mo;
		console.log(model)
	});

	$('#money').on('input propertychange', function() {
		var val = $(this).val();
		if(val != '' && !/^\d+$/.test(val)){
        	layer.msg("请填写整数金额。");
        	return false;
        } else {
        	if(val < 5) {
        		$("#statA p.tips").show();
        	} else {
        		$("#statA p.tips").hide();
        	}
        }
		$("#JOBnum").html(val*10);
	});

	$("#banknum").blur(function(){
		var val = $(this).val();
		CheckBankNo(val);
	});

	$("#Buy").on('tap',function(){

		if(model == "A"){
			var name = $('#username').val();
			if(name == ''){
				layer.msg("请填写买家姓名。");
				return false;
			}

			var userid = "{{ userinfo['id'] }}"

			var banknum = $('#banknum').val();
			if(banknum == ''){
				layer.msg("请填写银行卡号。");
				return false;
			}
			if(!CheckBankNo(banknum)){
				return false;
			}

			var bankname = $('#bankname').val();
			if(bankname == ''){
				layer.msg("请填写银行名称。");
				return false;
			}
		}

		if(model == "B"){

			var aliname = $("#alipayname").val();
			if(aliname == ''){
				layer.msg("请填写支付宝昵称。");
				return false;
			}

		}

		if(model == "C"){

			var wenname = $("#wechatname").val();
			if(wenname == ''){
				layer.msg("请填写微信昵称。");
				return false;
			}

		}

		var money = $('#money').val();
		if(money == ''){
			layer.msg("请填写充值金额。");
			return false;
		}
		if(money != '' && !/^\d+$/.test(money)){
        	layer.msg("请填写整数金额。");
        	return false;
        }
        if(money < 5){
        	layer.msg("单笔最少需充值5元。");
        	return false;
        }

        var moneyB = (Math.random()*(0.99-0.01) + 0.01).toFixed(2);
        var moneyC = (parseInt(money) + parseFloat(moneyB)).toFixed(2);
        console.log(moneyC);

        $(".paynum").text(moneyC);

        console.log(model)

        indexA = layer.open({
			type: 1,
			title:false,
			closeBtn:false,
			style: "padding:15px;",
			content: $("#Waiting"),
			area: ['80%', 'auto'],
			shadeClose: false,
			time:0
		});

        if(model == "A"){
	        $.post('/mjob/buycoin',{
	        	"paytype":"bank",
	        	"name":name,
	        	"bank_name":bankname,
	        	"bank_no":banknum,
	        	"money":moneyC
	        },function(data){
	        	if(data.error_code =="0"){
	        		$(".agent").text(data.result.name);
	        		$("#agentName").text(data.result.real_name);
	        		$("#agentBank").text(data.result.bank_name + ' ' + data.result.bank_sub);
	        		$("#agentBankno").text(data.result.bank_no);
	        		$("#qq").text(data.result.qq);

	        		NowTime = new Date(); 
					EndTime = NowTime.getTime() + 1000*60*30;
					setTime();

					layer.close(indexA);
					indexB = layer.open({
						type: 1,
						title:false,
						closeBtn:false,
						style: "padding:15px;",
						content: $("#Tip"),
						area: ['80%', 'auto'],
						shadeClose: false,
						time:0
					});
	        	}
	        },'json');
        }
        if(model == "B"){
        	$.post('/mjob/buycoin',{
	        	"paytype":"alipay",
	        	"name":aliname,
	        	"money":moneyC
	        },function(data){
	        	if(data.error_code =="0"){
	        		$(".agent").text(data.result.name);
	        		$("#alipayName").text(data.result.alipay_no);
	        		$("#QRcode img").attr('src',data.result.alipay_img);
	        		$("#qq").text(data.result.qq);

	        		NowTime = new Date(); 
					EndTime = NowTime.getTime() + 1000*60*30;
					setTime();

					layer.close(indexA);
					indexB = layer.open({
						type: 1,
						title:false,
						closeBtn:false,
						style: "padding:15px;",
						content: $("#Tip"),
						area: ['80%', 'auto'],
						shadeClose: false,
						time:0
					});
	        	}
	        },'json');
        }
        if(model == "C"){
        	$.post('/mjob/buycoin',{
	        	"paytype":"weixin",
	        	"name":wenname,
	        	"money":moneyC
	        },function(data){
	        	if(data.error_code =="0"){
	        		$(".agent").text(data.result.name);
	        		$("#wechatName").text(data.result.weixin_no);
	        		$("#QRcode img").attr('src',data.result.weixin_img);
	        		$("#qq").text(data.result.qq);

	        		NowTime = new Date(); 
					EndTime = NowTime.getTime() + 1000*60*30;
					setTime();

					layer.close(indexA);
					indexB = layer.open({
						type: 1,
						title:false,
						closeBtn:false,
						style: "padding:15px;",
						content: $("#Tip"),
						area: ['80%', 'auto'],
						shadeClose: false,
						time:0
					});
	        	}
	        },'json');
        }
		// indexA = layer.open({
		// 	type: 1,
		// 	title:false,
		// 	closeBtn:false,
		// 	style: "padding:15px;",
		// 	content: $("#Waiting"),
		// 	area: ['80%', 'auto'],
		// 	shadeClose: false,
		// 	time:3000,
		// 	end:function(){
		// 		NowTime = new Date(); 
		// 		EndTime = NowTime.getTime() + 1000*60*30;
		// 		setTime();
		// 		layer.close(indexA);
		// 		indexB = layer.open({
		// 			type: 1,
		// 			title:false,
		// 			closeBtn:false,
		// 			style: "padding:15px;",
		// 			content: $("#Tip"),
		// 			area: ['80%', 'auto'],
		// 			shadeClose: false,
		// 			time:0
		// 		});
		// 	}
		// });
	});

	$("#Next").on('tap',function(){
		layer.close(indexB);
		indexC = layer.open({
			type: 1,
			title:false,
			closeBtn:true,
			style: "padding:15px;",
			content: $("#Info"),
			area: ['90%', 'auto'],
			shadeClose: false,
			time:0,
			cancel: function(){ 
				layer.close(indexC);
				$("#statA").hide();
				$("#statB").show();
			}    
		});
	});

	$("#showAgent").on('tap',function(){
		indexC = layer.open({
			type: 1,
			title:false,
			closeBtn:true,
			style: "padding:15px;",
			content: $("#Info"),
			area: ['90%', 'auto'],
			shadeClose: false,
			time:0,
			cancel: function(){ 
				layer.close(indexC);
			}    
		});
	});

	//bankno为银行卡号
    function luhnCheck(bankno) {
	    var lastNum = bankno.substr(bankno.length - 1, 1); //取出最后一位（与luhn进行比较）
	    var first15Num = bankno.substr(0, bankno.length - 1); //前15或18位
	    var newArr = new Array();
	    for (var i = first15Num.length - 1; i > -1; i--) { //前15或18位倒序存进数组
	        newArr.push(first15Num.substr(i, 1));
	    }
	    var arrJiShu = new Array(); //奇数位*2的积 <9
	    var arrJiShu2 = new Array(); //奇数位*2的积 >9
	    var arrOuShu = new Array(); //偶数位数组
	    for (var j = 0; j < newArr.length; j++) {
	        if ((j + 1) % 2 == 1) { //奇数位
	            if (parseInt(newArr[j]) * 2 < 9) arrJiShu.push(parseInt(newArr[j]) * 2);
	            else arrJiShu2.push(parseInt(newArr[j]) * 2);
	        } else //偶数位
	        arrOuShu.push(newArr[j]);
	    }

	    var jishu_child1 = new Array(); //奇数位*2 >9 的分割之后的数组个位数
	    var jishu_child2 = new Array(); //奇数位*2 >9 的分割之后的数组十位数
	    for (var h = 0; h < arrJiShu2.length; h++) {
	        jishu_child1.push(parseInt(arrJiShu2[h]) % 10);
	        jishu_child2.push(parseInt(arrJiShu2[h]) / 10);
	    }

	    var sumJiShu = 0; //奇数位*2 < 9 的数组之和
	    var sumOuShu = 0; //偶数位数组之和
	    var sumJiShuChild1 = 0; //奇数位*2 >9 的分割之后的数组个位数之和
	    var sumJiShuChild2 = 0; //奇数位*2 >9 的分割之后的数组十位数之和
	    var sumTotal = 0;
	    for (var m = 0; m < arrJiShu.length; m++) {
	        sumJiShu = sumJiShu + parseInt(arrJiShu[m]);
	    }

	    for (var n = 0; n < arrOuShu.length; n++) {
	        sumOuShu = sumOuShu + parseInt(arrOuShu[n]);
	    }

	    for (var p = 0; p < jishu_child1.length; p++) {
	        sumJiShuChild1 = sumJiShuChild1 + parseInt(jishu_child1[p]);
	        sumJiShuChild2 = sumJiShuChild2 + parseInt(jishu_child2[p]);
	    }
	    //计算总和
	    sumTotal = parseInt(sumJiShu) + parseInt(sumOuShu) + parseInt(sumJiShuChild1) + parseInt(sumJiShuChild2);

	    //计算luhn值
	    var k = parseInt(sumTotal) % 10 == 0 ? 10 : parseInt(sumTotal) % 10;
	    var luhn = 10 - k;

	    if (lastNum == luhn) {
	        //console.log("验证通过");
	        return true;
	    } else {
	        layer.msg("银行卡号不规范，请检查");
	        return false;
	    }
	}

	//检查银行卡号
	function CheckBankNo(bankno) {
	    var bankno = bankno.replace(/\s/g, '');
	    if (bankno == "") {
	        layer.msg("请填写银行卡号");
	        return false;
	    }
	    var num = /^\d*$/; //全数字
	    if (!num.exec(bankno)) {
	        layer.msg("银行卡号必须全为数字");
	        return false;
	    }
	    if (bankno.length < 16 || bankno.length > 19) {
	        layer.msg("银行卡号长度必须在16到19之间");
	        return false;
	    }
	    //开头6位
	    var strBin = "10,18,30,35,37,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,58,60,62,65,68,69,84,87,88,94,95,98,99";
	    if (strBin.indexOf(bankno.substring(0, 2)) == -1) {
	        layer.msg("银行卡号开头6位不符合规范");
	        return false;
	    }
	    //Luhn校验
	    if (!luhnCheck(bankno)) {
	        return false;
	    }
	    var info = bankCardAttribution(bankno);
	    var bankname = info.bankName;
	    //console.log(bankname);
	    $('#bankname').val(bankname);
	    return true;
	}
</script>

{% endblock %}