{% extends "common/mobile-index.phtml" %}
{% block title  %}金职岛 - 数据板块{% endblock %}


{% block content %}
<style type="text/css">
	.bg {
		height: 20.5rem;
		background: #1f36bf url(/public/img/mjob/dataplatebg.png) center 30% no-repeat;
    	background-size: 80%;
	}
	.bg .cont {
		width: 75%;
		margin:0 auto;
		padding-top:3.62rem;
	}
	.bg .cont h3 {
		color:#fff;
		font-size:1.32rem;
		text-align: center;
		margin: 1rem 0;
	}
	.bg .cont p {
		color:#aab6ff;
		font-size:1rem;
		margin-top:2rem;
		line-height: 1.6rem;
	}
	.container h2 {
		margin-top: 2.85rem;
		font-size:1.56rem;
		text-align: center;
		color:#6f7178;
	}
	.container h3 {
		margin-top: 2.85rem;
		font-size:1.32rem;
		/*text-align: center;*/
		color:#6f7178;
		/*font-weight: 700;*/
	}
	.container div.line {
		background: #fac82e;
		width: 10%;
		height: .3rem;
		/*margin:0 auto;*/
	}
	.container div.line2 {
		background: #fac82e;
		width: 30%;
		height: .5rem;
		margin:0 auto;
	}
	.container p {
		margin-top:1.45rem;
		font-size:1.14rem;
		color:#9e9c9c;
		line-height: 1.8rem;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">数据板块</h1>
</header>

<div class="mui-content">
	<div class="bg">
		<div class="cont">
			<h3>数据板块将于金职链主链上线后开放</h3>
			<h3>敬请期待</h3>
			<p>当前金职岛居民的数据将会临时存放在侧链上，主链上线后，当前侧链上的数据将和个人的Data-Key绑定，将链上数据的控制权完全交给用户本人，数据只有在用户Data-Key授权的情况下才可以访问和获得。</p>
		</div>
	</div>
	<div class="container">
		<h2>数据上链的相关问答</h2>
		<div class="line2"></div>
		<h3>什么是职业数据上链？</h3>
		<div class="line"></div>
		<p>数据上链是指用户将自己的职业数据加密上传到基于ipfs方式的公网侧链，并在金职链（JOBChain）形成数据索引的过程。职业数据一旦上链，除了你本人的Data-Key授权解密外，任何个人或组织都没有能力获取到你的职业数据。</p>
		<h3>为什么要职业数据上链？</h3>
		<div class="line"></div>
		<p>我们个人的职业数据散布在众多第三方职业平台，甚至未经我们的同意就被平台销售、使用，而我们并没有获得任何直接收益。利用区块链技术，经过用户的授权，金职链帮助用户采集自己的职业数据并加密保存至区块链上，同时将职业数据私钥Data-Key交给用户自己管理，由用户完全掌握所有权和支配权，分享自己职业数据使用产生的价值，并生成自己的可信职业数字身份（G-ID），在与本人协作中大大降低信任成本。</p>
		<h3>职业数据上链对个人来说有什么利益？</h3>
		<div class="line"></div>
		<p>1、数据即资产，用户的职业数据中蕴藏着巨大的价值，职业数据被使用过程中产生的经济利益，将直接回馈给用户本人；
<br>2、职业数据上链后，任何职业数据使用的请求，都必须通过你本人的授权才能实现，确保个人拥有自己职业数据的所有权，不必担心职业数据被盗用而不知情的情况；
<br>3、基于多维度的职业数据，你可以构建属于自己的可信职业数字身份，在与人协作时、寻找资源时，大大降低别人信任、了解你的成本，提升了"职业连接"的效率。</p>
		<h3>为什么要分配Data-Key？</h3>
		<div class="line"></div>
		<p>Data-Key是唯一一把能解开链上数据的私钥，保存在客户端本地，只有用户本人掌控着这把唯一的钥匙，没有任何中心化数据库会存储用户的Data-Key信息。这种"去中心化"的技术实现方式，是区块链的核心特征之一。</p>
		<h3>丢失Data-Key会怎么样？如何备份？</h3>
		<div class="line"></div>
		<p>由于Data-Key是保存在本地客户端的，APP卸载或清理内存都可能导致Data-Key丢失。Data-Key一旦丢失，则意味着解开职业数据的唯一一把钥匙丢失，个人在金职链上的职业数据将永远无法读取和使用。因此，请务必保管好Data-Key。密钥保险箱是保管Data-Key的快捷方式，安全可靠，方便快捷，可按照说明进行一键备份。</p>
	</div>
</div>

{% endblock %}