{% extends "common/mobile-index.phtml" %}
{% block title  %}人脸识别{% endblock %}


{% block content %}
<style type="text/css">
	body,html,.mui-content {
		height:100%;
	}
	.imgbox {
		width: 17.09rem;
		height: 7.09rem;
		margin:0 auto;
		margin-top:4.66rem;
		margin-bottom: 2.9rem;
	}
	.imgbox img {
		max-width: 80%;
		max-height: 10rem;
	}
	.mui-icon,
	.mui-icon-extra {
	    display: inline-block;
	    margin-right: .5rem;
	    position: relative;
	    top: .1rem;
	}
	.mui-table-view-cell:after {
		left: 0;
	}
	h5 {
		font-size:1rem;
		margin:0;
		line-height: 1.4rem;
		color: #f50000;
	}
	.user span.mui-pull-right {
		color:#cfd0d5;
		position: relative;
    	top: .3rem;
	}
	.mui-table-view {
		border-radius: 4px;
		margin-top:1rem;
	}
	.mui-table-view:before,
	.mui-table-view:after {
		height: 0;
	}
	.usericon {
		display: inline-block;
		margin-right: .5rem;
		width: 1.5rem;
		height: 1.5rem;
		position: relative;
		top: .3rem;
	}
	.usericon.user-1 {
		background: url(/public/img/mjob/user-1.png) no-repeat center;
    	background-size: contain;
	}
	.usericon.user-2 {
		background: url(/public/img/mjob/ideicon4.png) no-repeat center;
    	background-size: contain;
	}
	.usericon.user-3 {
		background: url(/public/img/mjob/user-3.png) no-repeat center;
    	background-size: contain;
	}
	.usericon.user-4 {
		background: url(/public/img/mjob/ideicon3.png) no-repeat center;
    	background-size: contain;
	}
	.usericon.user-5 {
		background: url(/public/img/mjob/user-5.png) no-repeat center;
    	background-size: contain;
	}
	.mui-btn-block {
	    height: 4.62rem;
	    border-radius: 4.62rem;
	    font-size: 1.6rem;
	    width: 80%;
	    margin: 0 auto;
	    border: 1px solid #1de291;
	    background-color: #1de291;
	    margin-top: 2rem;
	}
	.mui-table-view-cell input {
		width: 60%;
		height:100%;
		border:none;
		margin:0;
		padding:0;
		position: relative;
		top:.4rem;
		text-align: right;
	}
	.inputrow {
		width: 50%;
		height: 4rem;
		margin:0 auto;
	}
	.fileinput-button {
        position: relative;
        display: block;
        overflow: hidden;
        width: 10rem;
        margin:0 auto;
    }
    .fileinput-button input{
        position:absolute;
        right: 0px;
        top: 0px;
        opacity: 0;
        -ms-filter: 'alpha(opacity=0)';
        font-size: 200px;
    }
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">人脸识别</h1>
</header>

<div class="mui-content">
	<div class="container">
		<div class="imgbox rel">
			<img src="/public/img/mjob/face.png" class="auto-center" id="showImage">
		</div>
		<div class="inputrow">
			<span class="btn btn-default fileinput-button">
	            <span>上传照片...</span>
	            <input type="file" accept="image/*" onchange="imgChange(event)" id="file">
	        </span>
		</div>
		
		<h5>*请点击上方按钮，上传清晰的人脸正面照片。</h5>
		<h5>*上传完成之后，可直接点击开始验证。</h5>

		<!-- <h5><a href="#">验证一下信息享受更高的数据权限</a></h5> -->
		<button type="button" id="confirmBtn" class="mui-btn mui-btn-success mui-btn-block">开始验证</button>

	</div>
</div>

<script type="text/javascript">

	var base;

	function imgChange(e) {
	    //console.info(e.target.files[0]);//图片文件
	    //var dom = $("#file");
	    //console.info(dom.value);//这个是文件的路径 C:\fakepath\icon (5).png
	    //console.log(e.target.value);//这个也是文件的路径和上面的dom.value是一样的
	    var reader = new FileReader();
	    reader.onload = (function (file) {
	        return function (e) {
	            //console.log(this.result); //这个就是base64的数据了
	            $("#showImage")[0].src=this.result;
	            base = this.result;
	            console.log(base);

	            // $.post("http://api.youtu.qq.com/youtu/api/detectface",{
	            // 	"app_id":appid,
	            // 	"image":base,
	            // 	"mode":mode
	            // },function(data){
	            // 	console.log(data);
	            // },'json');

	        };
	    })(e.target.files[0]);
	    reader.readAsDataURL(e.target.files[0]);
	    //console.log(base);
	}
	
	$('#confirmBtn').on('tap',function(){
		console.log(base);
	});

</script>

{% endblock %}