{% extends "common/mobile-index.phtml" %}
{% block title  %}金职岛 - 人脸识别{% endblock %}


{% block content %}
<style type="text/css">
	body,html,.mui-content {
		height:100%;
	}
	.imgbox {
		width: 17.09rem;
		height: 7.09rem;
		margin:0 auto;
		margin-top:4.66rem;
		margin-bottom: 2.9rem;
	}
	.imgbox img {
		max-width: 80%;
		max-height: 10rem;
	}
	.mui-icon,
	.mui-icon-extra {
	    display: inline-block;
	    margin-right: .5rem;
	    position: relative;
	    top: .1rem;
	}
	.mui-table-view-cell:after {
		left: 0;
	}
	h5 {
		font-size:1rem;
		margin:0;
		line-height: 1.4rem;
		color: #f50000;
	}
	.user span.mui-pull-right {
		color:#cfd0d5;
		position: relative;
    	top: .3rem;
	}
	.mui-table-view {
		border-radius: 4px;
		margin-top:1rem;
	}
	.mui-table-view:before,
	.mui-table-view:after {
		height: 0;
	}
	.usericon {
		display: inline-block;
		margin-right: .5rem;
		width: 1.5rem;
		height: 1.5rem;
		position: relative;
		top: .3rem;
	}
	.usericon.user-1 {
		background: url(/public/img/mjob/user-1.png) no-repeat center;
    	background-size: contain;
	}
	.usericon.user-2 {
		background: url(/public/img/mjob/ideicon4.png) no-repeat center;
    	background-size: contain;
	}
	.usericon.user-3 {
		background: url(/public/img/mjob/user-3.png) no-repeat center;
    	background-size: contain;
	}
	.usericon.user-4 {
		background: url(/public/img/mjob/ideicon3.png) no-repeat center;
    	background-size: contain;
	}
	.usericon.user-5 {
		background: url(/public/img/mjob/user-5.png) no-repeat center;
    	background-size: contain;
	}
	.mui-btn-block {
	    height: 4.62rem;
	    border-radius: 4.62rem;
	    font-size: 1.6rem;
	    width: 80%;
	    margin: 0 auto;
	    border: 1px solid #1de291;
	    background-color: #1de291;
	    margin-top: 2rem;
	}
	.mui-table-view-cell input {
		width: 60%;
		height:100%;
		border:none;
		margin:0;
		padding:0;
		position: relative;
		top:.4rem;
		text-align: right;
	}
	.inputrow {
		width: 50%;
		height: 4rem;
		margin:0 auto;
	}
	.fileinput-button {
        position: relative;
        display: block;
        overflow: hidden;
        width: 10rem;
        margin:0 auto;
    }
    .fileinput-button input{
        position:absolute;
        right: 0px;
        top: 0px;
        opacity: 0;
        -ms-filter: 'alpha(opacity=0)';
        font-size: 200px;
    }
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">人脸识别</h1>
</header>

<div class="mui-content">
	<div class="container">
		<div class="imgbox rel">
			<img src="/public/img/mjob/face.png" class="auto-center" id="showImage">
		</div>
		<div class="inputrow">
			<span class="btn btn-default fileinput-button">
	            <span>上传照片...</span>
	            <input type="file" accept="image/*" onchange="imgChange(event)" id="file">
	        </span>
		</div>
		
		<h5>*请点击上方按钮，上传清晰的人脸照片。</h5>
		<h5>*上传的图片上限大小为10Mb。</h5>
		<h5>*上传完成之后，请点击开始识别。</h5>

		<!-- <h5><a href="#">验证一下信息享受更高的数据权限</a></h5> -->
		<button type="button" id="confirmBtn" class="mui-btn mui-btn-success mui-btn-block">开始识别</button>

	</div>
</div>

<script type="text/javascript">

	var base;
	var indexload;

	function imgChange(e) {
	    //console.info(e.target.files[0]);//图片文件
	    //var dom = $("#file");
	    //console.info(dom.value);//这个是文件的路径 C:\fakepath\icon (5).png
	    //console.log(e.target.value);//这个也是文件的路径和上面的dom.value是一样的
	    var reader = new FileReader();
	    reader.onload = (function (file) {
	        return function (e) {
	        	if(e.total>10*1024*1024){
			        //alert('上传的图片的大于4M,请重新选择');
			        layer.msg('上传的图片的大于10M,请重新选择。',{icon: 5});
			        return false;
		        } else {
		        	var IMG = new Image();
		        	IMG.src = this.result;
		            IMG.onload = function(){
	      				var w = this.naturalWidth, h = this.naturalHeight , resizeW = 0, resizeH = 0;
	      				console.log(w,h)
	      			
		      			var maxSize = {
					        width: 1200,
					        height: 1000,
					        level: 0.6
					    };
					    if(w > maxSize.width || h > maxSize.height){
					        var multiple = Math.max(w / maxSize.width, h / maxSize.height);
					        resizeW = w / multiple;
					        resizeH = h / multiple;
					        var canvas = document.createElement('canvas'),
						    ctx = canvas.getContext('2d');
					        canvas.width = resizeW;
					        canvas.height = resizeH;
					        ctx.drawImage(IMG, 0, 0, resizeW, resizeH);
						    var base64 = canvas.toDataURL('image/jpeg', maxSize.level);
						    $("#showImage")[0].src=base64;
						    var arr = base64.split(',');
				            base = arr[1];
				            console.log(base)
					    } else {
					        // 如果图片尺寸小于最大限制，则不压缩直接上传
					        $("#showImage")[0].src=IMG.src;
				            var arr = IMG.src.split(',');
				            base = arr[1];
				            console.log(base);
					    }
					    
				    }
	        	
	            //console.log(this.result); //这个就是base64的数据了
		            // $("#showImage")[0].src=this.result;
		            // var arr = this.result.split(',');
		            // base = arr[1];
		            // console.log(base);
	            }
	        };
	    })(e.target.files[0]);
	    reader.readAsDataURL(e.target.files[0]);
	    //console.log(base);
	}
	
	$('#confirmBtn').on('tap',function(){
		if(!base){
			layer.msg('您尚未上传照片。',{icon: 5});
			return false;
		} else {
			indexload = layer.load(2, {
			  shade: [0.4,'#000'] //0.1透明度的白色背景
			});
			$.post('/mjob/checkface',{'imgbase64':base},function(data){
				if(data.error_code == '0'){
					layer.close(indexload);
					layer.msg('验证成功。',{icon: 1});
					setTimeout("window.location.href = 'promote'",2000);
				} else {
					layer.close(indexload);
					layer.msg("识别失败，请上传清晰的人脸照片。",{icon: 5});
				}
			},'json');
		}
	});

</script>

{% endblock %}