{% extends "common/mobile-index.phtml" %}
{% block title  %}我的身份{% endblock %}


{% block content %}
<style type="text/css">
	body,html,.mui-content {
		height:100%;
	}
	.imgbox {
		width: 7.09rem;
		height: 7.09rem;
		margin:0 auto;
		margin-top:2.66rem;
		margin-bottom: 1.9rem;
	}
	.mui-icon,
	.mui-icon-extra {
	    display: inline-block;
	    margin-right: .5rem;
	    position: relative;
	    top: .1rem;
	}
	.mui-table-view-cell:after {
		left: 0;
	}
	h5 {
		font-size:1rem;
		margin-bottom:.5rem;
		margin-top:2.4rem;
	}
	.user span.mui-pull-right {
		color:#cfd0d5;
		position: relative;
    	top: .3rem;
	}
	.mui-table-view {
		border-radius: 4px;
	}
	.mui-table-view:before,
	.mui-table-view:after {
		height: 0;
	}
	.usericon {
		display: inline-block;
		margin-right: .5rem;
		width: 1.5rem;
		height: 1.5rem;
		position: relative;
		top: .3rem;
	}
	.usericon.user-1 {
		background: url(/public/img/mjob/user-1.png) no-repeat center;
    	background-size: contain;
	}
	.usericon.user-2 {
		background: url(/public/img/mjob/ideicon4.png) no-repeat center;
    	background-size: contain;
	}
	.usericon.user-3 {
		background: url(/public/img/mjob/user-3.png) no-repeat center;
    	background-size: contain;
	}
	.usericon.user-4 {
		background: url(/public/img/mjob/ideicon3.png) no-repeat center;
    	background-size: contain;
	}
	.usericon.user-5 {
		background: url(/public/img/mjob/user-5.png) no-repeat center;
    	background-size: contain;
	}
	.mui-btn-block {
	    height: 4.62rem;
	    border-radius: 4.62rem;
	    font-size: 1.6rem;
	    width: 80%;
	    margin: 0 auto;
	    border: 1px solid #1de291;
	    background-color: #1de291;
	    margin-top: 2rem;
	}
	.mui-table-view-cell input {
		width: 60%;
		height:100%;
		border:none;
		margin:0;
		padding:0;
		position: relative;
		top:.4rem;
		text-align: right;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">我的身份</h1>
</header>

<div class="mui-content">
	<div class="container">
		<div class="imgbox rel">
			<img src="/public/img/mjob/face.png" class="auto-center">
		</div>
		<ul class="mui-table-view user">
			 <li class="mui-table-view-cell">
			 	<span class="user-1 usericon"></span>
			 	姓名
			 	<span class="mui-pull-right none">*正恩</span>
			 	<input type="text" name="name" value="金正恩" placeholder="请输入姓名" class="mui-pull-right">
			 </li>
	         <li class="mui-table-view-cell">
	         	<span class="user-2 usericon"></span>
			 	身份证号
			 	<span class="mui-pull-right none">44030******6598</span>
			 	<input type="text" name="cardid" value="440301199102088997" placeholder="请输入身份证号码" class="mui-pull-right">
			 </li>
		</ul>
		<h5><a href="#">验证一下信息享受更高的数据权限</a></h5>
		<button type="button" id="confirmBtn" class="mui-btn mui-btn-success mui-btn-block">验证身份</button>
		<ul class="mui-table-view verification none">
			<li class="mui-table-view-cell">
				<a class="mui-navigate-right">
					<span class="user-3 usericon"></span>人脸识别
				</a>
			</li>
			<li class="mui-table-view-cell">
				<a class="mui-navigate-right">
					<span class="user-4 usericon"></span>绑定钱包
				</a>
			</li>
			<li class="mui-table-view-cell">
				<a class="mui-navigate-right">
					<span class="user-5 usericon"></span>关注微信公众号
				</a>
			</li>
		</ul>
	</div>
</div>

<script type="text/javascript">
	function checkname(val) {
	    var regx = /^[\u4E00-\u9FA5\uf900-\ufa2d·s]{2,20}$/;
	    if(regx.test(val))
	    {
	        return true;
	    } else {
	        return false;
	    }
	}

	function checkcardid(val) {
	    var regx = /(^\d{15}$)|(^\d{18}$)|(^\d{17}(\d|X|x)$)/;  
	    if(regx.test(val))
	    {
	        return true;
	    } else {
	        return false;
	    }
	}

	$('#confirmBtn').on('tap',function(){
		var name = $("input[name='name']").val();
		var cardid = $("input[name='cardid']").val();
		if(name.length == ''){
	        layer.msg('请填写姓名。',{icon: 5});
	        return false;
	    }
	    if(!checkname(name)){
	    	layer.msg('请输入正确的姓名。',{icon: 5});
        	return false;
        }
	    if(!checkcardid(cardid)){
	    	layer.msg('身份证格式不正确',{icon: 5});
        	return false;
        }
        layer.msg('验证通过',{icon: 1});
	});
</script>

{% endblock %}