{% extends "common/mobile-index.phtml" %}
{% block title  %}金职岛 - 邀请好友{% endblock %}


{% block content %}
<style type="text/css">
	body, html {
	    background-color: #efeff4;
	}
	.banner {
		height: 12rem;
		position: relative;
		background: #1f36bf url("/public/img/mjob/recordbanner.png") no-repeat 50% 40%;
		background-size: 68%;
	}
	.banner div {
		font-size:4rem;
		color:#fff;
		text-align: center;
		width: 100%;
		height: 6.74rem;
		font-size:3rem;
	}
	.banner div span {
		position: absolute;
		top:0;
		left:0;
		bottom: 0;
		right:0;
		margin:auto;
		top: 2.5rem;
		width: 8.35rem;
		height: 1.3rem;
		font-size: 1rem;
	}
	.box {
		position: relative;
		top:-2.6rem;
	}
	.box > div {
		background: #fff;
		border-radius: 1rem;
		margin-bottom: 1rem;
		padding: 1.45rem;
	}
	.box > div .title {
		font-size:1.33rem;
		width: 7.33rem;
		text-align: center;
		margin: 0 auto;
    	margin-bottom: 1.25rem;
		padding: .2rem 0;
		border-bottom:2px solid #f8e940;
	}
	.box .myfriends .row-1 .col-xs-6 {
		text-align: center;
	}
	.box .myfriends .row-1 .col-xs-6 span {
		display: inline-block;
		margin-left: .3rem;
	}
	.box .myfriends .row-2 {
		margin-top:2rem;
	}
	/*.box .myfriends .row-2 .col-xs-6:first-child {
		border-right: 1px solid #d7dae7;
	}*/
	.box .myfriends .row-2 .col-xs-12 h3 {
		font-size:2.28rem;
		text-align: center;
		margin:0;
		margin-bottom: 1.2rem;
	}
	.box .myfriends .row-2 .col-xs-12 p {
		font-size:1rem;
		text-align: center;
		margin:0;
		color:#d1d0d0;
	}
	.box .rules p {
		color:#65676e;
	}
	.mui-btn-block {
	    height: 4.62rem;
	    border-radius: 4.62rem;
	    font-size: 1.6rem;
	    width: 80%;
	    margin: 0 auto;
	    border: 1px solid #1de291;
	    background-color: #1de291;
	    margin-top: 1rem;
	    margin-bottom: 5rem;
	}
	.mui-bar-nav~.mui-content {
		padding-bottom: 5rem;
	}
</style>


<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">邀请好友</h1>
</header>

<div class="mui-content">
	<div class="banner">
		<div class="auto-center">{{ data['code_system'] }}<span>我的邀请码</span></div>
	</div>
	<div class="container rel">
		<div class="box">
			<div class="myfriends">
				<div class="title">我的战绩</div>
				<div class="row row-1">
					<div class="col-xs-6">一级好友数<span>{{ data['count1'] }}</span></div>
					<div class="col-xs-6">二级好友数<span>{{ data['count2'] }}</span></div>
				</div>
				<div class="row row-2">
					<div class="col-xs-12">
						<h3>{{ data['jobcoin'] }}</h3>
						<p>累计获得JOB币</p>
					</div>
					<!-- <div class="col-xs-6">
						<h3>{{ data['candy'] }}</h3>
						<p>累计获得Candy</p>
					</div> -->
				</div>
			</div>
			<div class="rules">
				<div class="title">奖励规则</div>
				<p>1、每邀请一个好友完成注册，你可获得20 JOB的奖励。</p>
				<p>2、你邀请的好友，其邀请一个好友（即你的二级好友）完成注册时，你可获得10 JOB的奖励。</p>
				<p>3、金职链拥有法律范围内对于活动的最终解释权，并将严查虚假邀请行为，一经发现将取消奖励资格。</p>
			</div>
		</div>
		<a href="invitecard" id="confirmBtn" class="mui-btn mui-btn-success mui-btn-block">生成专属邀请卡</a>
	</div>
</div>

{% endblock %}