{% extends "common/mobile-index.phtml" %}
{% block title  %}金职岛 - 邀请卡{% endblock %}


{% block content %}
<style type="text/css">
	body,html{
        background-color: #000;
        /*padding:0 20px;*/
    }
	img {
		width: 100%;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">邀请卡</h1>
</header>

<div class="mui-content">
	<img src="{{ data['qrimg'] }}" />
</div>

{% endblock %}