{% extends "common/mobile-index.phtml" %}
{% block title  %}金职岛 - 邀请卡{% endblock %}


{% block content %}
<style type="text/css">
	body,html{
        background-color: #1f36bf;
        /*padding:0 20px;*/
    }
	.banner {
	    height: 12rem;
	    position: relative;
	    background: #1f36bf;
	}
	.banner div.bg {
	    width: 100%;
	    height: 6rem;
	    position: absolute;
	    top: 0;
	    left: 0;
	    right: 0;
	    bottom: 0;
	    margin: auto;
	    background: url(/public/img/mjob/recordbanner.png) no-repeat 50% top;
	    background-size: 83%;
	}
	.banner div.auto-center {
	    color: #fff;
	    text-align: center;
	    width: 100%;
	    height: 4.74rem;
	    font-size: 3rem;
	    /* top: -1rem; */
	}
	.banner div img {
	    width: auto;
	}
	.container {
		background: #fff;
		border-radius: 2rem;
		width: 90%;
		position: relative;
		top:-2rem;
		padding-bottom: 3rem;
	}
	.container h2,
	.container h3,
	.container h4,
	.container h5 {
		text-align: center;
	}
	.container h2 {
		color:#1f36bf;
		font-size:3.04rem;
		margin-top:3rem;
	}
	.container h4 {
		font-size:1.33rem;
		color:#8e8c8c;
	}
	.container h3 {
		color:#65676e;
		font-size:1.4rem;
		margin:3.4rem 0;
	}
	.container hr {
		height: 0;
		border:none;
		border:1px dotted #efefef;
		margin:3.4rem 0;
	}
	.container h5 {
		color:#65676e;
		font-size:1.4rem;
	}
	.container img {
		display: block;
		width: 9.15rem;
		height: 9.15rem;
		margin:1rem auto;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">邀请卡</h1>
</header>

<div class="mui-content">
	<div class="banner">
		<div class="bg"></div>
		<div class="auto-center"><img src="/public/img/mjob/landlogo2.png" class="auto-center"></div>
	</div>
</div>
<div class="container">
	<h2>{{ data['code_system'] }}</h2>
	<h4>我的邀请码</h4>
	<h3>"一起来金职岛挖掘职业数据财富吧"</h3>
	<hr>
	<h5>我是“{{ data['username'] }}”，金职岛第{{ data['userrank'] }}号居民</h5>
	<h5>我在金职岛等你，不见不散</h5>
	<img src="http://qr.liantu.com/api.php?text=http://www.jobchain.us/mjob/index?invitecode={{ data['code_system'] }}"/>
	<h5>扫码进入金职岛</h5>
</div>

{% endblock %}