{% extends "common/mobile-index.phtml" %}
{% block title  %}金职岛 - 主页{% endblock %}


{% block content %}
	<style>
		body,html{
            background-color: #1f36bf;
            /*padding:0 20px;*/
        }
        .mui-slider-indicator.mui-segmented-control {
            position: absolute !important;
            bottom: 0 !important;
            top: auto !important;
            left: 0 !important;
            height: 5.82rem !important;
            z-index:100 !important;
            /*border-top: .5rem solid #f7f7f7;*/
        }
        .mui-bar {
        	position: absolute !important;
        	z-index:100 !important;
        }
        .mui-bar-tab {
        	height:auto;
        }
		.mui-bar~.mui-content .mui-fullscreen {
			top: 44px;
			height: auto;
		}
		.mui-pull-top-tips {
			position: absolute;
			top: -20px;
			left: 50%;
			margin-left: -10px;
			width: 40px;
			height: 40px;
			border-radius: 100%;
			z-index: 1;
		}
		.mui-bar~.mui-pull-top-tips {
			top: 24px;
		}
		.mui-pull-top-wrapper {
			width: 42px;
			height: 42px;
			display: block;
			text-align: center;
			background-color: #efeff4;
			border: 1px solid #ddd;
			border-radius: 25px;
			background-clip: padding-box;
			box-shadow: 0 4px 10px #bbb;
			overflow: hidden;
		}
		.mui-pull-top-tips.mui-transitioning {
			-webkit-transition-duration: 200ms;
			transition-duration: 200ms;
		}
		.mui-pull-top-tips .mui-pull-loading {
			/*-webkit-backface-visibility: hidden;
			-webkit-transition-duration: 400ms;
			transition-duration: 400ms;*/
			
			margin: 0;
		}
		.mui-pull-top-wrapper .mui-icon,
		.mui-pull-top-wrapper .mui-spinner {
			margin-top: 7px;
		}
		.mui-pull-top-wrapper .mui-icon.mui-reverse {
			/*-webkit-transform: rotate(180deg) translateZ(0);*/
		}
		.mui-pull-bottom-tips {
			text-align: center;
			background-color: #efeff4;
			font-size: 15px;
			line-height: 40px;
			color: #777;
			display: none;
		}
		.mui-pull-top-canvas {
			overflow: hidden;
			background-color: #fafafa;
			border-radius: 40px;
			box-shadow: 0 4px 10px #bbb;
			width: 40px;
			height: 40px;
			margin: 0 auto;
		}
		.mui-pull-top-canvas canvas {
			width: 40px;
		}
		.mui-control-item .mui-tab-label {
			font-weight: 700;
		}
		.mui-segmented-control.mui-scroll-wrapper .mui-control-item {
			padding: 0;
			width: 30%;
			position: relative;
				top: .5rem;
		}
		.mui-slider-indicator .mui-icon {
			font-size: 24px;
			line-height:1;
			width: 54px;
		    display: block;
		    padding: 0;
		    margin: 0 auto;
		    padding-top: 10px;
		    border:none;
		}
		/*.mui-bar-tab {
			height: 5.82rem;
		}*/
		.mui-fullscreen.mui-slider .mui-slider-group {
			padding-bottom: 5rem;
		}
		/*.mui-scroll {
			display: none;
		}*/
		.powerrow {
			margin-top:1.52rem;
		}
		.powerrow .left {
			/*width: 6.2rem;*/
			height: 4.37rem;
			line-height: 4.37rem;
		}
		.powerrow .left span.mintit {
			width: 3.49em;
			height: 2.15rem;
			background: url("/public/img/mjob/minetit.png") center no-repeat;
			background-size: contain;
			display: inline-block;
			margin-right: 1rem;
			position: relative;
			top:.3rem;
		}
		.powerrow .left .power {
			font-size: 1.8rem;
		    color: #fac82e;
		    position: relative;
		    top: -.2rem;
		}
		/*.powerrow .left  {
			color:#6d82ff;
			font-size:.5rem;
			position: relative;
			top:-1rem;
		}*/
		.powerrow .right {
			display: block;
			width: 7.08rem;
			height: 2.66rem;
			border-radius: 2.66rem;
			font-size:1.14rem;
			line-height: 2.66rem;
			text-align: center;
			background-color: #3552fc;
			color:#fff;
			position: relative;
			top: .7rem;
		}
		.mine {
			height: 18rem;
			background: url("/public/img/mjob/minebg.png") center no-repeat;
			background-size: cover;
			margin-bottom: 2rem;
		}
		.mine .mining {
			display: block;
			width: 29.2% !important;
			height:10.9rem;
			margin:0 auto;
			position:relative;
			z-index: 5;
			/*margin-top:3.29rem;*/
		}
		
		@-webkit-keyframes hammer {
			0%   {
					-webkit-transform:rotate(-10deg);
							transform:rotate(-10deg);
				 }
			50%  {
					-webkit-transform:rotate(60deg);
							transform:rotate(60deg);
				 }
			100% {
					-webkit-transform:rotate(-10deg);
							transform:rotate(-10deg);
				 }
		}
		@keyframes hammer {
			0%   {transform:rotate(-10deg);-ms-transform:rotate(-10deg);-moz-transform:rotate(-10deg);-o-transform:rotate(-10deg);}
			50%  {transform:rotate(60deg);-ms-transform:rotate(60deg);-moz-transform:rotate(60deg);-o-transform:rotate(60deg);}
			100% {transform:rotate(-10deg);-ms-transform:rotate(-10deg);-moz-transform:rotate(-10deg);-o-transform:rotate(-10deg);}
		}
		.mine .mining .rock {
			position:absolute;
			z-index: -1;
			width: 80%;
		    height: 100%;
		    top: -2.5rem;
		    right: -2.5rem;
			transform:rotate(-10deg);
			-ms-transform:rotate(-10deg);
			-moz-transform:rotate(-10deg);
			-webkit-transform:rotate(-10deg);
			-o-transform:rotate(-10deg);
			-webkit-animation: hammer 1.5s 0s infinite;
					animation: hammer 1.5s 0s infinite;
			/*-webkit-animation-name: hammerHit;
			-webkit-animation-duration: 1.5s;
			-webkit-animation-iteration-count: infinite*/;
		}
		@keyframes hidCloud {
			0%   {opacity: .7;bottom:1rem;}
			50%  {opacity: 1;bottom:1.3rem;}
			100% {opacity: .7;bottom:1rem;}
		}
		@-webkit-keyframes hidCloud {
			0%   {opacity: .7;bottom:1rem;}
			50%  {opacity: 1;bottom:1.3rem;}
			100% {opacity: .7;bottom:1rem;}
		}
		.mine .mining .cloud {
			position:absolute;
			width: 6rem;
			height: 2rem;
			bottom:1rem;
			left:.2rem;
			opacity: .7;
			animation: hidCloud 2s infinite;
			-webkit-animation: hidCloud 2s infinite;
		}
		@keyframes fireworkA {
			0%   {opacity: 0;top:1.8rem;left:2.3rem;}
			25%  {opacity: 1;top:1.15rem;left:1.85rem;}
			50%  {opacity: .2;top:.5rem;left:1.4rem;}
			75%  {opacity: 0;top:.5rem;left:1.4rem;}
			100% {opacity: 0;top:1.8rem;left:2.3rem;}
		}
		@-webkit-keyframes fireworkA {
			0%   {opacity: 0;top:1.8rem;left:2.3rem;}
			25%  {opacity: 1;top:1.15rem;left:1.85rem;}
			50%  {opacity: .2;top:.5rem;left:1.4rem;}
			75%  {opacity: 0;top:.5rem;left:1.4rem;}
			100% {opacity: 0;top:1.8rem;left:2.3rem;}
		}
		@keyframes fireworkB {
			0%   {opacity: 0;top:1.9rem;left:2.4rem;}
			25%  {opacity: 1;top:2.0rem;left:1.85rem;}
			50%  {opacity: .2;top:2.1rem;left:1.3rem;}
			75%  {opacity: 0;top:2.1rem;left:1.3rem;}
			100% {opacity: 0;top:1.9rem;left:2.4rem;}
		}
		@-webkit-keyframes fireworkB {
			0%   {opacity: 0;top:1.9rem;left:2.4rem;}
			25%  {opacity: 1;top:2.0rem;left:1.85rem;}
			50%  {opacity: .2;top:2.1rem;left:1.3rem;}
			75%  {opacity: 0;top:2.1rem;left:1.3rem;}
			100% {opacity: 0;top:1.9rem;left:2.4rem;}
		}
		@keyframes fireworkC {
			0%   {opacity: 0;top:2rem;left:2rem;}
			25%  {opacity: 1;top:1.5rem;left:2.3rem;}
			50%  {opacity: .2;top:1rem;left:2.6rem;}
			75%  {opacity: 0;top:1rem;left:2.6rem;}
			100% {opacity: 0;top:2rem;left:2rem;}
		}
		@-webkit-keyframes fireworkC {
			0%   {opacity: 0;top:2rem;left:2rem;}
			25%  {opacity: 1;top:1.5rem;left:2.3rem;}
			50%  {opacity: .2;top:1rem;left:2.6rem;}
			75%  {opacity: 0;top:1rem;left:2.6rem;}
			100% {opacity: 0;top:2rem;left:2rem;}
		}
		.mine .mining .firework {
			position: absolute;
			width: 1.2rem;
			height: 1.2rem;
			/*animation-delay:1.5s;
			-webkit-animation-delay:1.5s;*/
		}
		.mine .mining .firework1 {
			top:1.8rem;
			left:2.3rem;
			opacity: 0;
			animation: fireworkA 1.5s linear 1s infinite;
			-webkit-animation: fireworkA 1.5s linear 1s infinite;
		}
		.mine .mining .firework2 {
			top:1.9rem;
			left:2.4rem;
			transform: scale(.7);
			opacity: 0;
			animation: fireworkB 1.5s linear 1s infinite;
			-webkit-animation: fireworkB 1.5s linear 1s infinite;
		}
		.mine .mining .firework3 {
			top:2rem;
			left:2rem;
			transform: scale(.85);
			opacity: 0;
			animation: fireworkC 1.5s linear 1s infinite;
			-webkit-animation: fireworkC 1.5s linear 1s infinite;
		}
		.mine .pmining {
			width: 8.22rem;
			height: 2.15rem;
			line-height: 2.15rem;
			border-radius: 2.15rem;
			text-align: center;
			background-color: #3552fc;
			color:#fff;
			font-size:1rem;
			margin:0 auto;
			margin-top:2rem;
			/*margin-bottom: 2rem;*/
		}
		.mine .ptext {
			color:#fff;
			font-size:1rem;
			text-align: center;
			margin-bottom: 2rem;
		}
		.subjectrow {
			position: relative;
			z-index: 10;
		}
		.subjectrow .subject {
			width: 5.32rem;
			margin-right: 1rem;
			display: block;
		}
		.subjectrow span.goldenup {
			position: absolute;
		    display: block;
		    width: 1rem;
		    height: 2rem;
		    left: 2.2rem;
		    top: 1rem;
		    background: url(/public/img/mjob/subject1.png) center no-repeat;
		    background-size: contain;
		    z-index: 3;
		    animation: goldenUp linear .5s 1;
			-webkit-animation: goldenUp linear .5s 1;
		}
		@keyframes goldenUp {
			0%   {top:0px;}
			50%  {top:-3rem;}
			100% {top:1rem;}
		}
		@-webkit-keyframes goldenUp {
			0%   {top:0px;}
			50%  {top:-3rem;}
			100% {top:1rem;}
		}
		.subjectrow span.showgold {
			position: absolute;
		    display: block;
		    width: 5rem;
		    height: 1rem;
		    font-size:1rem;
		    text-align: center;
		    color:#e7e7e7;
		    left: .1rem;
		    top: -1.5rem;
		    z-index: 4;
		    animation: showGold linear 1.2s 1;
			-webkit-animation: showGold linear 1.2s 1;
		}
		@keyframes showGold {
			0%   {top:-1.5rem;}
			100% {top:-5rem;opacity: 0;}
		}
		@-webkit-keyframes showGold {
			0%   {top:-1.5rem;}
			100% {top:-5rem;opacity: 0;}
		}
		.subjectrow .subject .radius {
			width: 4.17rem;
			height: 4.17rem;
			border-radius: 50%;
			background-color: #3552fc;
			margin:0 auto;
		}
		.subjectrow .subject .radius img {
			max-width: 2rem;
		}
		.subjectrow .subject .tit {
			width: 100%;
			height: 1.7rem;
			line-height: 1.7rem;
			border-radius: 1.7rem;
			text-align: center;
			font-size:1rem;
			background-color: #3552fc;
			color:#fff;
			margin-top:.6rem;
		}
		.news {
			width: 100%;
			height: 3.23rem;
			line-height: 3.23rem;
			border-radius: 3.23rem;
			background-color: #3552fc;
			margin-top: 1.2rem;
			margin-bottom: 1.64rem;
			color:#fff;
			padding:0 1.2rem;
			font-size: 1rem;
		}
		.news a {
			color:#fff;
		}
		.news span {
			display: inline-block;
			width: 3.48rem;
			height: 1.96rem;
			line-height: 1.96rem;
			border-radius: 1.96rem;
			text-align: center;
			background-color: #fe4b28;
			margin-right: .3rem;
		}
		.datalist {
			padding:.63rem;
		}
		.datalist h2 {
			font-size:1.33rem;
			color:#fff;
			margin:0;
		}
		.datalist .line {
			width: 2.05rem;
			height: .44rem;
			background-color: #fff;
			border-top-right-radius: .22rem;
			border-bottom-right-radius: .22rem;
			margin-top:.69rem;
			margin-bottom: 1.2rem;
		}
		.miningdata .row {
			margin-bottom: .8rem;
			font-size:1.13rem;
		}
		.miningdata .row .left {
			color:#adb9ff;
		}
		.miningdata .row .right {
			text-align: right;
		}
		.miningdata hr {
			border:0;
			background-color:#647bff;
			height:1px;
			margin-bottom: 0;
		}
		.ranking h2 > span { 
			float:right;
			font-size:1rem;
			position: relative;
			top: .25rem;
		}
		.ranking h2 > span::before {
			content: "";
		    background: url(/public/img/mjob/time.png);
		    background-size: contain;
		    width: 1rem;
		    height: 1rem;
		    position: absolute;
		    top: 0;
		    left: -1.5rem;
		    display: block;
		}
		.yellowtype {
			color:#ffdc19;
		}
		table.ranktable {
			font-size:1rem;
			width: 100%;
		}
		table.ranktable th {
			color:#a4b0fb;
		}
		table.ranktable tr {
			height: 2.3rem;
		}
		table.ranktable tbody .rank,
		table.ranktable tbody .name {
			color:#fff;
		}
		table.ranktable tbody .rank {
			text-align: center;
		}
		table.ranktable tbody .power {
			text-align: right;
		}
		table.ranktable tr:first-child td:first-child,
		table.ranktable tr:nth-child(2) td:first-child,
		table.ranktable tr:nth-child(3) td:first-child {
			color:#1f36bf;
		}
		table.ranktable tr:first-child td:first-child {
			background: url('/public/img/mjob/no1.png') no-repeat center;
			background-size: 1.33rem 1.83rem;
		}
		table.ranktable tr:nth-child(2) td:first-child {
			background: url('/public/img/mjob/no2.png') no-repeat center;
			background-size: 1.33rem 1.83rem;
		}
		table.ranktable tr:nth-child(3) td:first-child {
			background: url('/public/img/mjob/no3.png') no-repeat center;
			background-size: 1.33rem 1.83rem;
		}

		#tabbar-with-chat .banner {
			height: 12rem;
			position: relative;
			background: #1f36bf;
		}
		#tabbar-with-chat .banner div.bg {
			width: 100%;
		    height: 6rem;
		    position: absolute;
		    top: 0;
		    left: 0;
		    right: 0;
		    bottom: 0;
		    margin: auto;
		    background: url(/public/img/mjob/recordbanner.png) no-repeat 50% top;
		    background-size: 88%;
		}
		#tabbar-with-chat .banner div.auto-center {
			color:#fff;
			text-align: center;
			width: 100%;
			height: 4.74rem;
			font-size:3rem;
			/*top:-1rem;*/
		}
		#tabbar-with-chat .banner div img {
			width:auto;
		}
		#tabbar-with-chat .box {
			position: relative;
			top:-2.6rem;
		}
		#tabbar-with-chat .box > div {
			background: #fff;
			border-radius: 1rem;
			margin-bottom: 1rem;
			padding: 1.45rem;
		}
		#tabbar-with-chat .box > div .title {
			font-size:1.33rem;
			width: 10.33rem;
			text-align: center;
			margin: 0 auto;
	    	margin-bottom: 1.25rem;
			padding: .2rem 0;
			border-bottom:2px solid #f8e940;
		}
		#tabbar-with-chat .box > div .det {
			position: relative;
			left:1rem;
		}
		#tabbar-with-chat .box > div .det::before {
			content: "";
			display: block;
			width: 1rem;
			height: 100%;
			position: absolute;
			top:.5rem;
			left:-1.5rem;
			background: url("/public/img/mjob/pageline.png") no-repeat center;
			background-size: contain;
		}
		#tabbar-with-chat .box .myfriends .row-2 .col-xs-6:first-child {
			border-right: 1px solid #d7dae7;
		}
		#tabbar-with-chat .box .myfriends .row-2 .col-xs-6 h3 {
			font-size:2.28rem;
			text-align: center;
			margin:0;
			margin-bottom: .6rem;
		}
		#tabbar-with-chat .box .myfriends .row-2 .col-xs-6 p {
			font-size:1rem;
			text-align: center;
			margin:0;
			color:#d1d0d0;
		}
		#tabbar-with-chat .box .rules h3 {
			font-size: 1.14rem;
		}
		#tabbar-with-chat .box .rules p {
			color:#b1b0b0;
		}
		#tabbar-with-contact .banner {
			height: 7rem;
			position: relative;
			background: #1f36bf url("/public/img/mjob/recordbanner.png") no-repeat center;
			background-size: contain;
		}
		#tabbar-with-contact .box {
			position: relative;
			top:-2.6rem;
		}
		#tabbar-with-contact .box > div {
			background: #fff;
			border-radius: 1rem;
			margin-bottom: 1rem;
			overflow: hidden;
		}
		#tabbar-with-contact .box .myfriends {
			padding: 1.45rem;
		}
		#tabbar-with-contact .mui-table-view-cell:after {
			left: 0;
		}
		#tabbar-with-contact .mui-table-view .mui-media-object {
			height: 6.83rem;
			max-width: inherit;
			width: 6.83rem;
			display: inline-block;
			border-radius: 50%;
			overflow: hidden;
			background: #56d87a;
			position:relative;
		}
		#tabbar-with-contact .mui-table-view .mui-media-object .text {
			color:#fff;
			font-size:4rem;
			text-align: center;
			width: 4rem;
			height: 4rem;
			line-height: 4rem;
		}
		#tabbar-with-contact .mui-table-view .mui-media-body {
			margin-top: 1.2rem;
			font-size: 2rem;
		}
		#tabbar-with-contact .rules a.mui-navigate-right span {
			display: inline-block;
			margin-right: .5rem;
			width: 1.5rem;
			height: 1.5rem;
			position: relative;
			top:.3rem;
		}
		#tabbar-with-contact .rules a.mui-navigate-right span.ident1 {
			background: url("/public/img/mjob/ideicon1.png") no-repeat center;
			background-size: contain;
		}
		#tabbar-with-contact .rules a.mui-navigate-right span.ident2 {
			background: url("/public/img/mjob/ideicon2.png") no-repeat center;
			background-size: contain;
		}
		#tabbar-with-contact .rules a.mui-navigate-right span.ident3 {
			background: url("/public/img/mjob/ideicon3.png") no-repeat center;
			background-size: contain;
		}
		#tabbar-with-contact .rules a.mui-navigate-right span.ident4 {
			background: url("/public/img/mjob/ideicon4.png") no-repeat center;
			background-size: contain;
		}
		#tabbar-with-contact .rules a.mui-navigate-right span.ident5 {
			background: url("/public/img/mjob/ideicon5.png") no-repeat center;
			background-size: contain;
		}
		.minesbox {
			position: relative;
			height:16rem;
		}
		.minesbox .mines {
			float:left;
			position: absolute;
			width: 6.26rem;
			height: 9.63rem;
			transform: scale(.8);
		}
		.minesbox .mines .animatebox {
			position: relative;
			animation: myfloat 2s infinite;
			-webkit-animation: myfloat 2s infinite;
		}
		@keyframes myfloat {
			0%   {top:0px;}
			50%  {top:-.3rem;}
			100% {top:0px;}
		}
		@-webkit-keyframes myfloat {
			0%   {top:0px;}
			50%  {top:-.3rem;}
			100% {top:0px;}
		}
		/*.minesbox .mines .animatebox.aniA {
			animation: myfloatA 2.7s infinite;
			-webkit-animation: myfloatA 2.7s infinite;
		}
		@keyframes myfloatA {
			0%   {top:0px;}
			50%  {top:-.5rem;}
			100% {top:0px;}
		}
		@-webkit-keyframes myfloatA {
			0%   {top:0px;}
			50%  {top:-.5rem;}
			100% {top:0px;}
		}
		.minesbox .mines .animatebox.aniB {
			animation: myfloatB 3.7s infinite;
			-webkit-animation: myfloatB 3.7s infinite;
		}
		@keyframes myfloatB {
			0%   {top:0px;}
			50%  {top:-.4rem;}
			100% {top:0px;}
		}
		@-webkit-keyframes myfloatB {
			0%   {top:0px;}
			50%  {top:-.4rem;}
			100% {top:0px;}
		}*/
		.minesbox .mines .mineimg {
			width: 6.26rem;
			height: 7.98rem;
			background: url("/public/img/mjob/mine.png") no-repeat center;
			background-size: contain;
		}
		.minesbox .mines .minenum {
			width: 6.26rem;
			height: 2.15rem;
			line-height: 2.15rem;
			border-radius: 2.15rem;
			color:#fff;
			font-size:1.14rem;
			position: relative;
			top:-.5rem;
			opacity: .8;
			text-align: center;
			background: #314df3;
		}
		.mui-slider-indicator .iconpng {
		    width: 2rem;
		    height: 2rem;
		    display: block;
		    margin: 0 auto;
		    position: relative;
		    top: 4px;
		}
		.mui-slider-indicator .iconpng.icon-1 {
			background: url("/public/img/mjob/s1.png") center no-repeat;
			background-size: contain;
		}
		.mui-slider-indicator .iconpng.icon-2 {
			background: url("/public/img/mjob/s2.png") center no-repeat;
			background-size: contain;
		}
		.mui-slider-indicator .iconpng.icon-3 {
			background: url("/public/img/mjob/s3.png") center no-repeat;
			background-size: contain;
		}
		.mui-active .icon-1 {
			background: url("/public/img/mjob/s1s.png") center no-repeat !important;
			background-size: contain !important;
		}
		.mui-active .icon-2 {
			background: url("/public/img/mjob/s2s.png") center no-repeat !important;
			background-size: contain !important;
		}
		.mui-active .icon-3 {
			background: url("/public/img/mjob/s3s.png") center no-repeat !important;
			background-size: contain !important;
		}
		.mui-segmented-control.mui-segmented-control-inverted .mui-control-item.mui-active {
			color: #374fff !important;
		}	
		@-webkit-keyframes rotate_pacman_half_up {
		  0% {
		    -webkit-transform: rotate(270deg);
		            transform: rotate(270deg); }

		  50% {
		    -webkit-transform: rotate(360deg);
		            transform: rotate(360deg); }

		  100% {
		    -webkit-transform: rotate(270deg);
		            transform: rotate(270deg); } }

		@keyframes rotate_pacman_half_up {
		  0% {
		    -webkit-transform: rotate(270deg);
		            transform: rotate(270deg); }

		  50% {
		    -webkit-transform: rotate(360deg);
		            transform: rotate(360deg); }

		  100% {
		    -webkit-transform: rotate(270deg);
		            transform: rotate(270deg); } }

		@-webkit-keyframes rotate_pacman_half_down {
		  0% {
		    -webkit-transform: rotate(90deg);
		            transform: rotate(90deg); }

		  50% {
		    -webkit-transform: rotate(0deg);
		            transform: rotate(0deg); }

		  100% {
		    -webkit-transform: rotate(90deg);
		            transform: rotate(90deg); } }

		@keyframes rotate_pacman_half_down {
		  0% {
		    -webkit-transform: rotate(90deg);
		            transform: rotate(90deg); }

		  50% {
		    -webkit-transform: rotate(0deg);
		            transform: rotate(0deg); }

		  100% {
		    -webkit-transform: rotate(90deg);
		            transform: rotate(90deg); } }

		@-webkit-keyframes pacman-balls {
		  75% {
		    opacity: 0.7; }

		  100% {
		    -webkit-transform: translate(-100px, -6.25px);
		            transform: translate(-100px, -6.25px); } }

		@keyframes pacman-balls {
		  75% {
		    opacity: 0.7; }

		  100% {
		    -webkit-transform: translate(-100px, -6.25px);
		            transform: translate(-100px, -6.25px); } }

		.pacman {
		    width: 6rem;
			height: 48rem;
		}
		  .pacman > div:nth-child(2) {
		    -webkit-animation: pacman-balls 1s 0s infinite linear;
		            animation: pacman-balls 1s 0s infinite linear; }
		  .pacman > div:nth-child(3) {
		    -webkit-animation: pacman-balls 1s 0.33s infinite linear;
		            animation: pacman-balls 1s 0.33s infinite linear; }
		  .pacman > div:nth-child(4) {
		    -webkit-animation: pacman-balls 1s 0.66s infinite linear;
		            animation: pacman-balls 1s 0.66s infinite linear; }
		  .pacman > div:nth-child(5) {
		    -webkit-animation: pacman-balls 1s 0.99s infinite linear;
		            animation: pacman-balls 1s 0.99s infinite linear; }
		  .pacman > div:first-of-type {
		    width: 0px;
		    height: 0px;
		    border-right: 25px solid transparent;
		    border-top: 25px solid #ffde00;
		    border-left: 25px solid #ffde00;
		    border-bottom: 25px solid #ffde00;
		    border-radius: 25px;
		    -webkit-animation: rotate_pacman_half_up 0.5s 0s infinite;
		            animation: rotate_pacman_half_up 0.5s 0s infinite; }
		  .pacman > div:nth-child(2) {
		    width: 0px;
		    height: 0px;
		    border-right: 25px solid transparent;
		    border-top: 25px solid #ffde00;
		    border-left: 25px solid #ffde00;
		    border-bottom: 25px solid #ffde00;
		    border-radius: 25px;
		    -webkit-animation: rotate_pacman_half_down 0.5s 0s infinite;
		            animation: rotate_pacman_half_down 0.5s 0s infinite;
		    margin-top: -50px; }
		  .pacman > div:nth-child(3), .pacman > div:nth-child(4), .pacman > div:nth-child(5), .pacman > div:nth-child(6) {
		    background-color: #ffde00;
		    width: 15px;
		    height: 15px;
		    border-radius: 100%;
		    margin: 2px;
		    width: 10px;
		    height: 10px;
		    position: absolute;
		    -webkit-transform: translate(0, -6.25px);
		        -ms-transform: translate(0, -6.25px);
		            transform: translate(0, -6.25px);
		    top: 25px;
		    left: 100px; }

		    #goDb {
		    	display: block;
		    	width: 100%;
		    	height:6.87rem;
		    	margin-bottom: 1rem;
		    	border-radius: .5rem;
		    	background: #eaeaea url("/public/img/mjob/2.png") center no-repeat !important;
				background-size: contain !important;
				line-height: 6.87rem;
				font-size: 2rem;
				text-align: center;
		    }
	</style>

	<!-- <header class="mui-bar mui-bar-nav">
		<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
		<h1 class="mui-title">金职岛</h1>
	</header> -->
	<div class="mui-content">
		<div id="slider" class="mui-slider mui-fullscreen">
			
			<div class="mui-slider-group">
				<div id="tabbar" class="mui-slider-item mui-control-content mui-active">
					<div class="mui-scroll-wrapper">
						<div class="mui-scroll scroll">
							<div class="container">
								<div class="powerrow">
									<div class="left">
										<span class="mintit"></span><span class="power showpower">{{ data['score'] }}</span>
									</div>
									<a href="strategy" class="right">算力攻略</a>
									<audio id="audio" src="/public/sound/gold.mp3" preload='auto'></audio>
									<div class="cls"></div>
								</div>
								<div class="mine">
									<div class="nomine none">
										<p class="ptext">算力越高挖出的矿石越多哦</p>
										<div class="mining">
											<img src="/public/img/mjob/mining2.png" class="auto-center">
											<div class="rock">
												<img src="/public/img/mjob/hammer2.png" class="auto-center">
											</div>
											<div class="cloud">
												<img src="/public/img/mjob/cloud.png" class="auto-center">
											</div>
											<div class="firework firework1">
												<img src="/public/img/mjob/firework.png" class="auto-center">
											</div>
											<div class="firework firework2">
												<img src="/public/img/mjob/firework.png" class="auto-center">
											</div>
											<div class="firework firework3">
												<img src="/public/img/mjob/firework.png" class="auto-center">
											</div>
										</div>
										<p class="pmining">正在挖矿中…</p>
									</div>
									<div class="hasmine ">
										<p class="ptext">72小时内不领取金矿将消失</p>
										<div class="minesbox">
											<!-- <div class="mines">
												<div class="mineimg"></div>
												<div class="minenum">0.00035</div>
											</div> -->
										</div>
									</div>
									<div class="loader-inner pacman auto-center">
								        <div></div>
								        <div></div>
								        <div></div>
								        <div></div>
								        <div></div>
							        </div>
								</div>
								<div class="subjectrow">
									<!-- <span class="showgold">+10.00</span> -->
									<!-- <span class="goldenup"></span> -->
									<a href="assets" class="subject left">
										<div class="radius rel">
											<img src="/public/img/mjob/subject1.png" class="auto-center">
										</div>
										<div class="tit">我的资产</div>
									</a>
									<a href="promote" class="subject left">
										<div class="radius rel">
											<img src="/public/img/mjob/subject2.png" class="auto-center">
										</div>
										<div class="tit">提升算力</div>
									</a>
									<a href="invite" class="subject right" style="margin-right: 0;">
										<div class="radius rel">
											<img src="/public/img/mjob/subject3.png" class="auto-center">
										</div>
										<div class="tit">邀请好友</div>
									</a>
									<div class="cls"></div>
								</div>
								<div class="news">
									<a href="#">
										<span>头条</span>
										金职岛开放注册，开启挖矿狂欢！
									</a>
								</div>
								<div class="miningdata datalist">
									<h2>挖矿数据</h2>
									<div class="line"></div>
									<div class="row">
										<div class="col-xs-6 left">我的当前挖矿能力</div>
										<div class="col-xs-6 right yellowtype showpower">{{ data['score'] }}</div>
									</div>
									<div class="row">
										<div class="col-xs-6 left">我的挖矿算力排名</div>
										<div class="col-xs-6 right yellowtype " id="Myrank">{{ data['scorerank'] }}</div>
									</div>
									<div class="row">
										<div class="col-xs-6 left">今日全民挖矿次数</div>
										<div class="col-xs-6 right yellowtype " id="Todaymining">{{ data['todaycount'] }}</div>
									</div>
									<div class="row">
										<div class="col-xs-6 left">累计全民挖矿次数</div>
										<div class="col-xs-6 right yellowtype " id="Allmining">{{ data['totalcount'] }}</div>
									</div>
									<hr>
								</div>
								<div class="ranking datalist" style="padding-bottom: 5rem;">
									<h2 class='rel'>全岛挖矿排行<span class="yellowtype">更新于 <span id='time'>{{ data['time'] }}</span></span></h2>
									<div class="line"></div>
									<table class="ranktable">
									    <thead>
										    <tr>
										        <th style="width:10%;text-align: center;">名次</th>
										        <th style="width:55%">账号</th>
										        <th style="width:30%;text-align: right;">算力值</th>
										    </tr>
									    </thead>
									    <tbody>
										{% for key, item in data['userlist'] %}
										    <tr>
										        <td class="rank">{{ key+1 }}</td>
										        <td class="name">{{ item['phone'] }}</td>
										        <td class="yellowtype power">{{ item['score'] }}</td>
										    </tr>
										{% endfor %}
									  </tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div id="tabbar-with-chat" class="mui-slider-item mui-control-content">
					<div class="mui-scroll-wrapper">
						<div class="mui-scroll">
							<div class="mui-content">
								<div class="banner">
									<div class="bg"></div>
									<div class="auto-center"><img src="/public/img/mjob/landlogo2.png" class="auto-center"></div>
								</div>
								<div class="container rel">
									<div class="box">
										<div class="myfriends">
											<div class="row row-2">
												<div class="col-xs-6">
													<h3>{{ data['totaluser'] }}</h3>
													<p>金职岛总人口</p>
												</div>
												<div class="col-xs-6">
													<h3>{{ data['totalvip'] }}</h3>
													<p>创世居民</p>
												</div>
											</div>
										</div>
										<a href="../db/index" id="goDb" class="none"> 金职夺宝 </a>
										<div class="rules">
											<div class="title">金职岛建设规划</div>
											<div class="det">
												<h3>搭建及完善金职岛</h3>
												<p>搭建金职岛基础设施，吸引创始居民及更多的居民入住，提供JOB币奖励，为后续的职业数据价值经济做好用户储备。</p>
												<h3>引进应用入岛</h3>
												<p>引进基于金职链的各类区块链职业应用，为岛上居民提供各方面的职业服务。</p>
												<h3>打造去中心化职业数据交易所</h3>
												<p>在金职岛内打造去中心化的职业数据交易所，引入职业数据买方，向岛上居民公平公正地进行数据采购，并将授权数据所获得的利益回报给岛上居民。</p>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div id="tabbar-with-contact" class="mui-slider-item mui-control-content">
					<div class="mui-scroll-wrapper">
						<div class="mui-scroll" style="height: 100%;">
							<div class="mui-content" style="height: 100%;">
								<div class="banner">
									<!-- <div class="auto-center"><img src="/public/img/mjob/landlogo.png" class="auto-center"></div> -->
								</div>
								<div class="container rel">
									<div class="box">
										<div class="myfriends">
											<ul class="mui-table-view">
												<li class="mui-table-view-cell mui-media">
													<span class="mui-media-object mui-pull-left">
														<span class="text auto-center">无</span>
													</span>
													<div class="mui-media-body">
														<span>{{ data['username'] }}</span>
														<p class="mui-ellipsis">金职岛第{{ data['userrank'] }}位居民</p>
													</div>
												</li>
											</ul>
										</div>
										<div class="rules">
											<ul class="mui-table-view">
												<li class="mui-table-view-cell none">
													<a href="dataplate" class="mui-navigate-right">
														<span class="ident1"></span>我的数据
													</a>
												</li>
												<li class="mui-table-view-cell">
													<a href="assets" class="mui-navigate-right">
														<span class="ident2"></span>我的资产
													</a>
												</li>
												<li class="mui-table-view-cell none">
													<a href="#" class="mui-navigate-right">
														<span class="ident3"></span>金职钱包
													</a>
												</li>
												<li class="mui-table-view-cell">
													<a href="identity" class="mui-navigate-right">
														<span class="ident4"></span>实名信息
													</a>
												</li>
												<li class="mui-table-view-cell">
													<a href="setting" class="mui-navigate-right">
														<span class="ident5"></span>账户设置
													</a>
												</li>
												<li class="mui-table-view-cell">
													<a href="javascript:void(0);" data-href="tabbar-with-chat" id="tomain2" class="mui-navigate-right">
														<span class="ident3"></span>关于金职岛
													</a>
												</li>
												<li class="mui-table-view-cell">
													<a href="aboutus" class="mui-navigate-right">
														<span class="ident1"></span>关于金职链
													</a>
												</li>
											</ul>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div id="sliderSegmentedControl" class="mui-scroll-wrapper mui-slider-indicator mui-segmented-control mui-segmented-control-inverted">
				<nav class="mui-bar mui-bar-tab">
					<a class="mui-control-item mui-active" data-href="tabbar" id="tabbar2">
						<span class="icon-1 iconpng"></span>
						<span class="mui-tab-label">数据挖矿</span>
					</a>
					<a class="mui-control-item" data-href="tabbar-with-chat" id="tabbar-with-chat2">
						<span class="icon-2 iconpng"><!-- <span class="mui-badge">9</span> --></span>
						<span class="mui-tab-label">金职夺宝</span>
					</a>
					<a class="mui-control-item" data-href="tabbar-with-contact" id="tabbar-with-contact2">
						<span class="icon-3 iconpng"></span>
						<span class="mui-tab-label">我的身份</span>
					</a>
				</nav>
			</div>
		</div>
	</div>
	
	<script type="text/javascript" src="{{url('js/mjob/mui.pullToRefresh.js')}}"></script>
	<script type="text/javascript" src="{{url('js/mjob/mui.pullToRefresh.material.js')}}"></script>
	<script>

		$('#tomain2').on('tap',function(){
			var href = $(this).attr('data-href');
			window.location.href = 'main#a-'+href;
			checkHref();
		})

		$('#sliderSegmentedControl a').on('tap',function(){
			var href = $(this).attr('data-href');
			//console.log(href);
			//window.location.href = 'main#'+href;
			if(href == "tabbar-with-chat") {
				window.location.href = '/db/index';
			} else {
				window.location.href = 'main#a-'+href;
			}
			//window.location.href = 'main#a-'+href;
			checkHref();
		});

		function checkHref(){
			var urlArr = window.location.href.split('#');
			var position = urlArr[1];
			var width = $(window).width();

			if(position == 'a-tabbar-with-chat'){
				$('#tabbar-with-chat').addClass('mui-active').siblings().removeClass('mui-active');
				$('#tabbar-with-chat2').addClass('mui-active').siblings().removeClass('mui-active');
				$('.mui-slider-group').css("transform","translate3d(-"+width+"px, 0px, 0px)");
			}
			else if(position == 'a-tabbar-with-contact'){
				$('#tabbar-with-contact').addClass('mui-active').siblings().removeClass('mui-active');
				$('#tabbar-with-contact2').addClass('mui-active').siblings().removeClass('mui-active');
				$('.mui-slider-group').css("transform","translate3d(-"+width*2+"px, 0px, 0px)");
			}
			else {
				$('#tabbar').addClass('mui-active').siblings().removeClass('mui-active');
				$('#tabbar2').addClass('mui-active').siblings().removeClass('mui-active');
				$('.mui-slider-group').css("transform","translate3d(0px, 0px, 0px)");
			}
		}
		checkHref();
		document.getElementById('slider').addEventListener('slide', function(e) {
			setTimeout(function(){
				var href = $('.mui-slider-item.mui-active').attr('id');
				window.location.href = 'main#a-'+href;
			},100)
			
		});

		//矿显示数量
		var minenum2 = 5;
		var minenum = minenum2;
		//显示范围
		var HRange = 16-9.63; 	//9.63
		var WRange = parseFloat($('.minesbox').css('width').replace('px','')) / parseFloat(window.getComputedStyle(document.documentElement)["fontSize"].replace('px','')) - 6.26;
		//本地储存金矿
		var result = {};
		//碰撞数组
		var positionArray = [];
		//最大随机次数
		var maxrandom = 0;
		//console.log(WRange,HRange)
		var audio = $("#audio")[0];

		function checkMines(){
			var len;
			$('.minesbox').each(function(){
				len = $(this).find('.mines').length;
				if(result.length != 0){
					if(len == 0) {
						result.splice(0,6)
						minenum = result.length >= minenum ? minenum : result.length;
						if(minenum > 0){
							showMines();
						} else {
							$('.hasmine').hide();
							$('.nomine').fadeIn(500);
						}
					} 
				} else {
					$('.hasmine').hide();
					$('.nomine').fadeIn(500);
				}
			});
		}

		function randomLeft(){
			maxrandom++;
			var returnLeft = Math.floor((Math.random()*WRange+1));
			//console.log('s'+$.inArray( returnLeft,positionArray )+':'+maxrandom);
			if(maxrandom >= 500){
				return returnLeft;
			}
			if($.inArray( returnLeft,positionArray ) >= 0){
				return randomLeft();
			} else {
				return returnLeft;
			}
		}

		function showMines(){
			positionArray = [];
			maxrandom = 0;
			for(var i = 0; i < minenum; i++){
				//var left = Math.floor((Math.random()*WRange+1));
				var left = randomLeft();
				//console.log(left)
				var top1 = Math.floor((Math.random()*HRange+1));
				var leftW = 2;
				//console.log(left,leftB)
				for(var kk = left-leftW; kk <= left + leftW; kk++){
					positionArray.push(kk);

				}
				var dom = "<div class='mines datacoin' data-id='"+i+"' data-mineid='"+result[i].jobcoinno+"' data-mine='"+result[i].jobcoin+"' style='left:"+left+"rem;top:"+top1+"rem;'>"
					// if(i%2 == 0){
					// 	dom +=    "<div class='animatebox aniA'>";
					// } else {
					// 	dom +=    "<div class='animatebox aniB'>";
					// }
					+	"<div class='animatebox'>"
					+		"<div class='mineimg'></div>"
					+		"<div class='minenum'>"+result[i].jobcoin+"</div>"
					+    "</div>"
					+ "</div>";
				$('.minesbox').append(dom);
				$('.mines').fadeIn(500);
				checkMines();			
			}
		}

		function getjobcoinno(){
			$('.minesbox').empty();
			$('.nomine').hide();
			$('.hasmine').hide();
			$('.pacman').show();
			$.get('/mjob/getjobcoinno',function(data){
				if(data.reason == "success"){
					$('.pacman').hide();
					if(data.result.length != 0){
						result = data.result;
						minenum = result.length >= minenum ? minenum : result.length;
						//console.log(minenum);
						showMines();
						$('.nomine').hide();
						$('.hasmine').fadeIn(500);
					} else {
						$('.hasmine').hide();
						$('.nomine').fadeIn(500);
					}
				} else {
					$('.pacman').hide();
					$('.hasmine').hide();
					$('.nomine').fadeIn(500);
				}
			},'json');
		}

		function checkName( name ) {
		    var regu = /[\u4E00-\u9FA5]/;
		    var re = new RegExp(regu);
		    if (re.test(name)) {
		        return true;  
		    }
		    else {
		        return false;
		    }
		};

		$(function(){
			if($.cookie('regscore') > 0){
				layer.msg("新用户注册，算力+"+$.cookie('regscore')+"。",{icon: 6,time:3500});
				$.cookie('regscore', null);
			} else {
				$.get('/mjob/checktodaylogin',function(data){
					if(data.reason == "success" && data.result.login_score != '0') {
						layer.msg("每日登陆，算力+"+data.result.login_score+"。",{icon: 6,time:3500});
					}
				},'json');
			}

			getjobcoinno();
			
			var text = $('.mui-media-body span').text();
			if(!checkName(text)){
				$('.mui-media-object .text').html('无');
			} else {
				$('.mui-media-object .text').html(text.substring(0,1));
			}

			audio.load();
			audio.play();
			audio.pause();

		});

		$('.minesbox').on('tap','.datacoin',function(){
			var _this = $(this);
			_this.removeClass('datacoin');
			var id = _this.attr('data-id');
			var mid = _this.attr('data-mineid');
			var mine = _this.attr('data-mine');
			//console.log(_this,$("[data-mineid='"+mid+"']"));
			//$('.minesbox').off('tap',$("[data-mineid='"+mid+"']"));
			//$("[data-mineid='"+mid+"']").off('tap');
			//$('.minesbox').off('tap',_this);

			result.splice(id,1,'');
			console.log(result);

			$.get('/mjob/editjobcoinno',{'jobcoinno':mid},function(data){},'json');

			audio.load();
			audio.play();

			_this.animate({
				left:"-1rem",
				top:"16rem",
				opacity:"0"
			},500,"linear",function(){
				_this.remove();
				checkMines();

				function domGold(){
					$('.subjectrow').prepend("<span class='showgold' id='"+mid+id+"'>+"+mine+"</span>");
				}

				setTimeout(domGold(),1100);
				setTimeout("$('#"+mid+id+"').remove()",1100);
			});

			$('.subjectrow').prepend("<span class='goldenup' id="+mid+"></span>");
			setTimeout("$('#"+mid+"').remove()",500);

		});

		mui.init();

		mui('.mui-scroll').on('tap','a',function(){document.location.href=this.href;});

		

		(function($) {
			//阻尼系数
			var deceleration = mui.os.ios?0.003:0.0009;
			$('.mui-scroll-wrapper').scroll({
				bounce: false,
				indicators: true, //是否显示滚动条
				deceleration:deceleration
			});
			$.ready(function() {
				//循环初始化所有下拉刷新，上拉加载。
				$.each(document.querySelectorAll('.mui-slider-group .scroll'), function(index, pullRefreshEl) {
					$(pullRefreshEl).pullToRefresh({
						down: {
							callback: function() {
								var self = this;
								setTimeout(function() {
									minenum = minenum2 ;
									getjobcoinno();
									//console.log('down')
									self.endPullDownToRefresh();
								}, 1000);
							}
						}
						// ,up: {
						// 	callback: function() {
						// 		var self = this;
						// 		setTimeout(function() {
						// 			reload();
						// 			console.log('up')
						// 			self.endPullUpToRefresh();
						// 		}, 1000);
						// 	}
						// }
					});
				});
			});
		})(mui);

	</script>
{% endblock %}