{% extends "common/mobile-index.phtml" %}
{% block title  %}金职岛 - 购买失败{% endblock %}


{% block content %}
<style type="text/css">
	body,html,.mui-content {
		height:100%;
	}
	.mui-content {
		background: #fff;
	}
	div img {
		max-width: 100%;
	}
	.box {
		margin-top:10rem;
	}
	.box .headbox {
		height: 12rem;
		width: 12rem;
		margin:0 auto;
		border-radius: 50%;
		overflow:hidden;
		position: relative;
		margin-bottom: 1rem;
	}
	.box p {
		text-align: center;
	}
	h5 {
		text-align: center;
	    font-size: 1rem;
	    position: fixed;
	    bottom: 5%;
	    width: 93%;
	    color:#a4a6ad;
	}
	h3 {
		text-align: center;
		color:#67686e;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">购买失败</h1>
</header>


<div class="mui-content">
	<div class="container">
		<div class="box">
			<div class="headbox">
				<img src="/public/img/mjob/failed.png" class="auto-center">
			</div>
			<h3>购买失败</h3>
			<p>代理商未正常收到您的有效转账</p>
		</div>
		<h5>对订单有疑问，请加代理商QQ联系 {{ data['agent'].qq }}</h5>
	</div>
</div>


{% endblock %}