{% extends "common/mobile-index.phtml" %}
{% block title  %}金职岛 - 订单详情{% endblock %}


{% block content %}
<style type="text/css">
	body,html,.mui-content {
		height:100%;
		background: #fff;
	}
	div img {
		max-width: 100%;
	}
	span.import {
		color:#f00;
	}
	p {
		font-size:1rem;
	}
	.box {
		margin-top:10rem;
	}
	.box .headbox {
		height: 8rem;
		width: 8rem;
		margin:0 auto;
		border-radius: 50%;
		overflow:hidden;
		position: relative;
		margin-bottom: 1rem;
	}
	.box p,
	.box a {
		text-align: center;
	}
	.box a {
		width: 100%;
		display: block;
		margin-bottom: 3rem;
	}
	h5 {
		margin-top:12rem;
		text-align: center;
		font-size:1rem;
	}
	#Info h6 {
		text-align: center;
	}
	#Info .infobox {
		border:1px solid #eee;
		background: #eee;
		padding:15px;
		margin-bottom: 2rem;
		margin-top:1rem;
	}
	#Info .infobox .infos {
		margin-bottom: 1rem;
		font-size:1rem;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">订单详情</h1>
</header>


<div class="mui-content">
	<div class="container">
		<div class="box">
			<div class="headbox">
				<img src="/public/img/db/1.jpg" class="auto-center">
			</div>
			<p>代理商<span class="import">{{ data['agent'].name }}</span>正在处理中，请稍后</p>
			<p>正常情况1小时内处理完毕，遇到订单高峰期，处理时间相应延长</p>
			<a href="javascript:void(0)" id="showAgent">显示代理商收款账号信息</a>
			{% if userinfo['id'] == 25 or userinfo['id'] == 27 %}
			<div>
				<button type="button" class="mui-btn mui-btn-success col-xs-4 left">充值成功{{ data['list'].id }}</button>
				<button type="button" class="mui-btn mui-btn-warning col-xs-4 right">充值失败{{ data['list'].id }}</button>
			</div>
			{% endif %}
		</div>
		<h5>对订单有疑问，请加代理商QQ联系 {{ data['agent'].qq }}</h5>
	</div>
</div>

<div id="Info" class="none">
	<div class="container">
		<div class=""></div>
		<div class="infobox">
			<div class="infos">
				<div class="row">
					<div class="col-xs-4">开户名</div>
					<div class="col-xs-8">{{ data['agent'].real_name }}</div>
				</div>
				<div class="row">
					<div class="col-xs-4">账户名称</div>
					<div class="col-xs-8">{{ data['agent'].bank_name }}  {{ data['agent'].bank_sub }}</div>
				</div>
				<div class="row">
					<div class="col-xs-4">银行卡号</div>
					<div class="col-xs-8">{{ data['agent'].bank_no }}</div>
				</div>
				<div class="row">
					<div class="col-xs-4">金额</div>
					<div class="col-xs-8"><span class="import paynum">{{ data['list'].money }}</span>元</div>
				</div>
			</div>
			<p>1、务必<span class="import">按指定的金额</span>转账，否则将无法完成购买（小数点后随机增加的金额是您该笔转账的专属凭证，且会与整数部分一同充入您的账户）</p>
			<p>2、转账时<span class="import">无需备注任何信息</span>，否则将会被代理商退回，无法完成充值</p>
			<p>3、请使用已在DragonEx绑定的本人银行卡转账(支持网上银行,手机银行)，<span class="import">禁止使用支付宝、微信、银联APP、ATM、POS机等第三方支付平台转账，否则将一律退回！！！</span></p>
		</div>
	</div>
</div>
<script type="text/javascript">

	$("#showAgent").on('tap',function(){
		var indexC = layer.open({
			type: 1,
			title:false,
			closeBtn:true,
			style: "padding:15px;",
			content: $("#Info"),
			area: ['80%', 'auto'],
			shadeClose: false,
			time:0,
			cancel: function(){ 
				layer.close(indexC);
			}    
		});
	});


</script>

{% endblock %}