{% extends "common/mobile-index.phtml" %}
{% block title  %}金职岛 - 订单记录{% endblock %}


{% block content %}
<style type="text/css">
	body,html,.mui-content {
		height:100%;
		background: #fff;
	}
	div img {
		max-width: 100%;
	}
	#segmentedControl {
		margin-top:1.5rem;
		font-size:1.6rem;
	}
	.mui-segmented-control.mui-segmented-control-inverted .mui-control-item {
		border-bottom: 2px solid #eee;
		font-size: 1.6rem;
		color:#67686e;
	}
	.mui-segmented-control.mui-segmented-control-inverted .mui-control-item.mui-active {
		border-bottom: 2px solid #fe0b8c;
		color:#67686e;
	}
	table {
		font-size:1rem;
		margin-top:1rem;
	}
	table thead th {
		color:#a4a6ad;
	}
	table thead th,
	table tbody td {
		text-align: center;
	}
	table tbody td span.mui-icon,
	table tbody td span.mui-icon-extra {
		font-size:.5rem;
	}
	.table>thead>tr>th {
		border:none;
		font-weight: 300;
	}
	.table>tbody>tr>td {
		/*border-top: 1px solid #eee;*/
		border:none;
	}
	h5 {
		text-align: center;
	    font-size: 1rem;
	    position: fixed;
	    bottom: 5%;
	    width: 93%;
	    color:#a4a6ad;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">订单记录</h1>
</header>


<div class="mui-content">
	<div class="container">
		<div id="segmentedControl" class="mui-segmented-control mui-segmented-control-inverted mui-segmented-control-primary">
			<a class="mui-control-item mui-active" href="#item1">处理中</a>
			<a class="mui-control-item" href="#item2">购买成功</a>
			<a class="mui-control-item" href="#item3">购买失败</a>
		</div>
		<div>
			<div id="item1" class="mui-control-content mui-active">
				<table class="table table-condensed">
					<thead>
					    <tr>
						    <th>订单号</th>
						    <th>金额</th>
						    <th>代理商</th>
						    <th>提交时间</th>
					    </tr>
					</thead>
				    <tbody>
						{% for key, item in data %}
						  	{% if item['pay_type'] == 'Wait' %}
								<tr data-id="{{ item['id'] }}" data-status="buying">
									<td>{{ item['id'] }}</td>
									<td>{{ item['money'] }}</td>
									<td>{{ item['agent_name'] }}
										{% if item['pay_method'] =='bank'  %}
											<span class="mui-icon-extra mui-icon-extra-card"></span>
										{% elseif item['pay_method'] =='alipay' %}
											<span class="mui-icon-extra mui-icon-extra-alipay"></span>
										{% elseif item['pay_method'] =='weixin' %}
											<span class="mui-icon mui-icon-weixin"></span>
										{% endif %}
									</td>
									<td>{{ item['create_time'] }}</td>
								</tr>
							{% endif %}
						{% endfor %}
				  </tbody>
				</table>
			</div>
			<div id="item2" class="mui-control-content">
				<table class="table table-condensed">
					<thead>
					<tr>
						<th>订单号</th>
						<th>金额</th>
						<th>代理商</th>
						<th>提交时间</th>
					</tr>
					</thead>
					<tbody>
					{% for key, item in data %}
						{% if item['pay_type'] == 'Y' %}
							<tr data-id="{{ item['id'] }}" data-status="done">
								<td>{{ item['id'] }}</td>
								<td>{{ item['money'] }}</td>
								<td>{{ item['agent_name'] }}
									{% if item['pay_method'] =='bank'  %}
										<span class="mui-icon-extra mui-icon-extra-card"></span>
									{% elseif item['pay_method'] =='alipay' %}
										<span class="mui-icon-extra mui-icon-extra-alipay"></span>
									{% elseif item['pay_method'] =='weixin' %}
										<span class="mui-icon mui-icon-weixin"></span>
									{% endif %}
								</td>
								<td>{{ item['create_time'] }}</td>
							</tr>
						{% endif %}
					{% endfor %}
					</tbody>
				</table>
			</div>
			<div id="item3" class="mui-control-content">
				<table class="table table-condensed">
					<thead>
					<tr>
						<th>订单号</th>
						<th>金额</th>
						<th>代理商</th>
						<th>提交时间</th>
					</tr>
					</thead>
					<tbody>
					{% for key, item in data %}
						{% if item['pay_type'] == 'N' %}
							<tr data-id="{{ item['id'] }}" data-status="failed">
								<td>{{ item['id'] }}</td>
								<td>{{ item['money'] }}</td>
								<td>{{ item['agent_name'] }}
									{% if item['pay_method'] =='bank'  %}
										<span class="mui-icon-extra mui-icon-extra-card"></span>
									{% elseif item['pay_method'] =='alipay' %}
										<span class="mui-icon-extra mui-icon-extra-alipay"></span>
									{% elseif item['pay_method'] =='weixin' %}
										<span class="mui-icon mui-icon-weixin"></span>
									{% endif %}
								</td>
								<td>{{ item['create_time'] }}</td>
							</tr>
						{% endif %}
					{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	<!--<h5>对订单有疑问，请加代理商QQ联系 1343884353</h5>-->
	</div>
</div>
<script type="text/javascript">

	$(document).on('tap','tr',function(){
		var id = $(this).attr('data-id');
		var stat = $(this).attr('data-status');
		if(stat == "buying"){
			window.location.href = "/mjob/orderstat/"+id;
		}
		if(stat == "done"){
			window.location.href = "/mjob/orderdone/"+id;
		}
		if(stat == "failed"){
			window.location.href = "/mjob/orderfailed/"+id;
		}
		//window.location.href = "/mjob/orderstat?id="+id;
	});
</script>

{% endblock %}