{% extends "common/mobile-index.phtml" %}
{% block title  %}金职岛 - 订单详情{% endblock %}


{% block content %}
<style type="text/css">
	body,html,.mui-content {
		height:100%;
		background: #fff;
	}
	div img {
		max-width: 100%;
	}
	span.import {
		color:#f00;
	}
	p {
		font-size:1rem;
	}
	.box {
		margin-top:8rem;
	}
	.box .headbox {
		height: 8rem;
		width: 8rem;
		margin:0 auto;
		border-radius: 50%;
		overflow:hidden;
		position: relative;
		margin-bottom: 1rem;
		margin-top: 4rem;
	}
	.box p,
	.box a {
		text-align: center;
	}
	.box a {
		width: 100%;
		display: block;
		text-decoration: underline;
		margin-top: 2rem;
		margin-bottom: 3rem;
	}
	h5 {
		text-align: center;
	    font-size: 1rem;
	    position: fixed;
	    bottom: 5%;
	    width: 93%;
	    color:#a4a6ad;
	}
	#Info h6,
	#Info .col-xs-4,
	#Info .col-xs-5 {
		color:#a4a6ad;
	}
	#Info .col-xs-4,
	#Info .col-xs-5 {
		text-align: right;
	}
	#Info .col-xs-8,
	#Info .col-xs-7 {
		padding-left: 0;
	}
	#Info .col-xs-8,
	#Info .col-xs-7
	#Info p {
		color:#67686e;
	}
	#Info p {
		margin-bottom: 5px !important;
	}
	#Info .infobox {
		border:1px solid #eee;
		background: #f4f5f9;
		padding:15px;
		margin-bottom: 2rem;
	}
	#Info .infobox .infos {
		margin-bottom: 1rem;
		font-size:1rem;
	}
	#Info .col-xs-2 {
		height: 0;
		padding:8%;
	}
	#Info .col-xs-10 {
		background: #e6e9fb;
		padding:10px;
		float:right;
	}
	#QRcode {
		height:6rem;
		margin:1rem auto;
		position: relative;
	}
	#QRcode .col-xs-5,
	#QRcode .col-xs-7 {
		height: 100%;
		line-height: 6rem;
		font-size:1rem;
	}
	#QRcode .col-xs-7 {
		width: 6rem;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">订单详情</h1>
</header>


<div class="mui-content">
	<div class="container">
		<div class="box">
			<div class="headbox">
				<img src="/public/img/mjob/head1.png" class="auto-center">
			</div>
			<p style="font-size:1.5rem;">代理商<span class="import">{{ data['agent'].name }}</span>正在处理中，请稍后</p>
			<p>正常情况1小时内处理完毕</p>
			<p>遇到订单高峰期，处理时间相应延长</p>
			<a href="javascript:void(0)" id="showAgent">显示代理商收款账号信息</a>
			{% if canadmin and data['list'].pay_type =='Wait'  %}
			<div>
				<button type="button" class="mui-btn mui-btn-success col-xs-4 left" data-stat="Y" data-id="{{ data['list'].id }}">充值成功</button>
				<button type="button" class="mui-btn mui-btn-warning col-xs-4 right"  data-stat="N" data-id="{{ data['list'].id }}">充值失败</button>
			</div>
			{% endif %}
		</div>
		<h5>对订单有疑问，请加代理商QQ联系 {{ data['agent'].qq }}</h5>
	</div>
</div>

<div id="Info" class="none">
	<div class="container">
		<div style="margin-top:10px;">
			<div class="col-xs-2 rel">
				<img src="/public/img/mjob/head1.png" class="auto-center">
			</div>
			<div class="col-xs-10">
				<p>您好，我是金职岛认证代理商<span class="agent">{{ data['agent'].name }}</span></p>
				<p>本次由我为您服务！</p>
				<p>请按要求转账至以下账户</p>
				<p>收到转账后，我会尽快为您充入JOB</p>
			</div>
			<div class="cls"></div>
		</div>
		<div class="infobox" style="margin-top:20px;">
			
				<div class="infos">
					{% if data['list'].pay_method =='bank'  %}
					<div class="row">
						<div class="col-xs-4">支付方式</div>
						<div class="col-xs-8">银行转账</div>
					</div>
					<div class="row">
						<div class="col-xs-4">开户名</div>
						<div class="col-xs-8">{{ data['agent'].real_name }}</div>
					</div>
					<div class="row">
						<div class="col-xs-4">账户名称</div>
						<div class="col-xs-8">{{ data['agent'].bank_name }}  {{ data['agent'].bank_sub }}</div>
					</div>
					<div class="row">
						<div class="col-xs-4">银行卡号</div>
						<div class="col-xs-8">{{ data['agent'].bank_no }}</div>
					</div>
					{% elseif data['list'].pay_method =='alipay' %}
					<div class="row">
						<div class="col-xs-5">支付方式</div>
						<div class="col-xs-7">支付宝转账</div>
					</div>
					<div class="row">
						<div class="col-xs-5">支付宝昵称</div>
						<div class="col-xs-7">{{ data['agent'].alipay_no }}</div>
					</div>
					{% elseif data['list'].pay_method =='weixin' %}
					<div class="row">
						<div class="col-xs-5">支付方式</div>
						<div class="col-xs-7">微信转账</div>
					</div>
					<div class="row">
						<div class="col-xs-5">微信昵称</div>
						<div class="col-xs-7">{{ data['agent'].weixin_no }}</div>
					</div>
					{% endif %}
					<div class="row">
						<!-- <div class="col-xs-4">金额</div>
						<div class="col-xs-8"><span class="import paynum">{{ data['list'].money }}</span>元</div> -->
						<div class="col-xs-12" style="text-align:center;font-size:1rem;margin-top:1rem;">金额 <span class="import paynum">{{ data['list'].money }}</span> 元</div>
					</div>
					{% if data['list'].pay_method =='alipay' %}
					<div id="QRcode">
						<div class="col-xs-5">支付二维码</div>
						<div class="col-xs-7 rel"><img src="{{ data['agent'].alipay_img }}" class="auto-center"></div>
					</div>
					{% endif %}
					{% if data['list'].pay_method =='weixin' %}
					<div id="QRcode">
						<div class="col-xs-5">支付二维码</div>
						<div class="col-xs-7 rel"><img src="{{ data['agent'].weixin_img }}" class="auto-center"></div>
					</div>
					{% endif %}
				</div>
				<p>1、务必<span class="import">按指定的金额</span>转账，否则将无法完成购买（小数点后随机增加的金额是您该笔转账的专属凭证，且会与整数部分一同充入您的账户）</p>
				<p>2、转账时<span class="import">无需备注任何信息</span>，否则将会被代理商退回，无法完成充值</p>
				{% if data['list'].pay_method =='bank'  %}
				<p>3、请使用本人银行卡转账(支持网上银行,手机银行)，<span class="import">禁止使用银联APP、ATM、POS机等第三方支付平台转账，否则将一律退回！！！</span></p>
				{% endif %}
			
		</div>
	</div>
</div>
<script type="text/javascript">

	$("#showAgent").on('tap',function(){
		var indexC = layer.open({
			type: 1,
			title:false,
			closeBtn:true,
			style: "padding:15px;",
			content: $("#Info"),
			area: ['90%', 'auto'],
			shadeClose: false,
			time:0,
			cancel: function(){ 
				layer.close(indexC);
			}    
		});
	});

	$("button").on('tap',function(){
		var id = $(this).attr('data-id');
		var stat = $(this).attr('data-stat');

		$.post('/mjob/changeorder',{"id":id ,"type":stat},function(data){
			if(data.error_code == "0"){
				layer.msg('操作成功。');
				setTimeout("window.location.href = '/mjob/orders'",2000);
			} else {
				layer.msg(data.reason);
			}
		},'json');
	});


</script>

{% endblock %}