{% extends "common/mobile-index.phtml" %}
{% block title  %}金职岛 - 订单详情{% endblock %}


{% block content %}
<style type="text/css">
	body,html,.mui-content {
		height:100%;
		background: #fff;
	}
	div img {
		max-width: 100%;
	}
	span.import {
		color:#f00;
	}
	p {
		font-size:1rem;
	}
	.box {
		margin-top:10rem;
	}
	.box .headbox {
		height: 8rem;
		width: 8rem;
		margin:0 auto;
		border-radius: 50%;
		overflow:hidden;
		position: relative;
		margin-bottom: 1rem;
	}
	.box p,
	.box a {
		text-align: center;
	}
	.box a {
		width: 100%;
		display: block;
		margin-bottom: 3rem;
	}
	h5 {
		margin-top:12rem;
		text-align: center;
		font-size:1rem;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">订单详情</h1>
</header>


<div class="mui-content">
	<div class="container">
		<div class="box">
			<div class="headbox">
				<img src="/public/img/db/1.jpg" class="auto-center">
			</div>
			<p>代理商<span class="import">鲁迅</span>正在处理中，请稍后</p>
			<p>正常情况1小时内处理完毕，遇到订单高峰期，处理时间相应延长</p>
			<a href="javascript:void(0)" id="showAgent">显示代理商收款账号信息</a>
			<div>
				<button type="button" class="mui-btn mui-btn-success col-xs-4 left">充值成功</button>
				<button type="button" class="mui-btn mui-btn-warning col-xs-4 right">充值失败</button>
			</div>
		</div>
		<h5>对订单有疑问，请加代理商QQ联系 1343884353</h5>
	</div>
</div>


{% endblock %}