{% extends "common/layout-index.phtml" %}
{% block title  %}JOBCHAIN - Home{% endblock %}
{% block header %}{{ partial('common/layout-header_en')}}{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{{url('css/particles/normalize.css')}}"/>
<!-- <link rel="stylesheet" type="text/css" href="{{url('css/particles/default.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{url('css/particles/style.css')}}"/> -->
<link rel="stylesheet" type="text/css" href="{{url('css/jquery.mCustomScrollbar.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{url('css/index/en.css')}}"/>

<div class="rows" id="F1">
	<div class="container">
		<div class="f1text">
			<h2>The decentralized</h2>
			<h2>career credit open platform based on</h2>
			<h2>Blockchain</h2>
			<p>JOBChain Aggregates B- and C-Users' Career Credit Data Fragments across Applications via Open Interfaces,synchronous data block hash to broadcast in Ethereum network,creating multi-dimensional and unchangeable user career credit portraits.Based on the career credit infrastructure provided by JOBChain,all occupational applications and products do not need to build a complex blockchain base, just transfer the platform interface built by the JOBChain,then we can access and jointly build this blockchain-based occupational credit ecology. </p>
			<a href="javascript:;">White Paper</a>
		</div>
		<div class="item1 abo" id="Item1"><div class="animation1 action1"></div></div>
		<div class="item1 abo" id="Item2"><div class="animation1 action2"></div></div>
		<div class="item1 abo" id="Item3"><div class="animation1 action3"></div></div>
		<div class="item1 abo" id="Item4"><div class="animation1 action4"></div></div>
		<div class="item2 abo" id="Item5"></div>
		<div class="item2 abo" id="Item6"></div>
		<div class="item3 abo" id="Item7"></div>
	</div>
</div>
<div class="rows" id="F2">
	<div class="container">
		<h3>The open platform which record user historical career credit data</h3>
		<h2>Decentralization <span>·</span> Tamperproof  <span>·</span> Smart contract</h2>
		<img src="/public/img/index/f2en.png">
	</div>
</div>
<div class="rows" id="F3">
	<div class="container">
		<h2>Hire or be hired <br>equivalent to Mining</h2>
		<p>JOB Coin will serve as an exchange unit for promoting multi-collaboration between multiple trust subjects,restricting the credit behavior of recruiters and applicants with smart contracts. JOBChain Inspires more trusted agents to record their career credits to the open platform, providing credit data buyers with more secure and more efficient credit data consumption solutions at the same time.</p>
		<img src="/public/img/index/f3en.png">
	</div>
</div>
<div class="rows" id="F4">
	<div id="F4particles"></div>
	<div class="container">
		<div class="towerbox">
			<div class="ob2 abo t2"><img src="/public/img/index/f4-2.png"></div>
			<div class="ob2 abo t3"><img src="/public/img/index/f4-3.png"></div>
			<div class="ob2 abo t4"><img src="/public/img/index/f4-3.png"></div>
			<div class="ob1 abo t1"><img src="/public/img/index/f4-1.png"></div>
		</div>
		<h2>JOBChain</h2>
		<h2>JOBChain career Credit Open Platform · Interface</h2>
		<div class="F4link">
			<a href="/index/api" class="left">JOBChain Interface></a>
			<a href="javascript:;" class="right">Mining Rules></a>
		</div>
	</div>
</div>
<div class="rows" id="F5">
	<div class="container">
		<div class="titlerow r1">Founding Team</div>
		<div class="peoplerow">
			<div class="peoplebox">
				<div class="boxs left">
					<div class="headimg">
						<img src="/public/img/index/zhongshaofeng.png">
					</div>
					<h4>ShaoFeng Zhong</h4>
					<p>Co-founder of Zhi Jin Capital</p>
					<p>Founder of Lovingjob.com</p>
				</div>
				<div class="boxs left">
					<div class="headimg">
						<img src="/public/img/index/xuminjie.png">
					</div>
					<h4>MinJie Xu</h4>
					<p>Accenture Hong Kong Google Project Members</p>
					<p>Master of Information Engineering, CUHK</p>
				</div>
				<div class="boxs left">
					<div class="headimg"></div>
					<h4>×</h4>
					<p>×</p>
					<p>×</p>
				</div>
			</div>
		</div>
		<div class="titlerow r2">Team Consultants</div>
		<div class="peoplerow">
			<div class="peoplebox">
				<div class="boxs left">
					<div class="headimg"></div>
					<h4>×</h4>
					<p>×</p>
					<p>×</p>
				</div>
				<div class="boxs left">
					<div class="headimg"></div>
					<h4>×</h4>
					<p>×</p>
					<p>×</p>
				</div>
				<div class="boxs left">
					<div class="headimg"></div>
					<h4>×</h4>
					<p>×</p>
					<p>×</p>
				</div>
			</div>
		</div>
		<div class="titlerow r3">Investment Agency</div>
		<div class="textrow">
			<div class="left">Yun Shi Capital</div>
			<div class="left">Squirrel Capital</div>
			<div class="left">Lin Shi Capital</div>
			<div class="left">LIGHTER</div>
		</div>
	</div>
</div>
<div class="rows" id="F6">
	<div class="container">
		<div class="tit">
			<img src="/public/img/index/f6en.png">
		</div>
		<h2 id="F7">Landing Application Example Based On JOBChain</h2>
		<h3>Accumulatively opened up<span>302,000+</span>users’ career credit data</h3>
		<div class="connection">
			<div class="connectionrows">
				<div class="boxs left">
					<div class="imgbox">
						<img src="/public/img/index/connection1.png" class="auto-center">
					</div>
					<h4>Lovingjob.com</h4>
					<p>Lovingjob.com has opened a total of 17 cities and districts part-time networks, including Beijing,Shanghai,Guangzhou,Shenzhen...service more than 15,000 enterprise recruitment users, cumulative service 500000 + a part-time job applicants.</p>
				</div>
				<div class="boxs left">
					<div class="imgbox">
						<img src="/public/img/index/connection2.jpg" class="auto-center">
					</div>
					<h4>Shortcut Information Technology Co., Ltd.</h4>
					<p>Shortcut Information Technology Co., Ltd. is a vertical recruitment website focused on undergraduate internships. It has 130,000+ college intern users and provides internship recruitment service for more than 500 Fortune 500 and industry giants from various industries.</p>
				</div>
				<div class="boxs left">
					<div class="imgbox">
						<img src="/public/img/index/connection3.png" class="auto-center">
					</div>
					<h4>Meimei Network Technology Co., Ltd.</h4>
					<p>Meimei Network Technology Co., Ltd. is a matching trading platform for building models and businesses. Based on the real-name system, it provides real, reliable and fast model information and peripheral services to provide models with the best advertising platform and faster development opportunities. There are already 120,000+ model users.</p>
				</div>
				<div class="boxs left">
					<div class="imgbox">
						
					</div>
					<h4>Part-time Home</h4>
					<p>Part-time Home establishes a two-way smart contract based on blockchain technology for each recruiter and part-time applicant, and records the evaluation and credit of recruiters and job applicants on the blockchain. Based on the credit history of the recruiter and job applicants, Part-time Home help the job applicants to choose a better-credit recruiter, and also help the recruiter find a credit better job applicants.</p>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="rows" id="F8">
	<div class="container">
		<h2>CONTACTS</h2>
		<div class="contactsrow">
			<div class="box">
				<a href="javascript:;"><img src="/public/img/index/f7-1.png" class="auto-center"></a>
				<a href="javascript:;"><img src="/public/img/index/f7-2.png" class="auto-center"></a>
				<a href="javascript:;"><img src="/public/img/index/f7-3.png" class="auto-center"></a>
				<a href="javascript:;"><img src="/public/img/index/f7-4.png" class="auto-center"></a>
				<a href="javascript:;"><img src="/public/img/index/f7-5.png" class="auto-center"></a>
				<a href="javascript:;"><img src="/public/img/index/f7-6.png" class="auto-center"></a>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="{{url('js/particles/particles.js')}}"></script>
<script type="text/javascript" src="{{url('js/particles/app.js')}}"></script>
<script type="text/javascript" src="{{url('js/jquery.mousewheel.min.js')}}"></script>
<script type="text/javascript" src="{{url('js/jquery.mCustomScrollbar.concat.min.js')}}"></script>
<script type="text/javascript">
	// $(document).scroll( function(){
	//     var me = arguments.callee; //匿名函数可以 通过 arguments.callee 调用自己
	//     me.doc = me.doc || $(document); //缓存 $(document);
	//     me.head = me.head || $('header');
	//     me.lastTop = me.lastTop || me.doc.scrollTop();
	//     if( me.doc.scrollTop() < 20 ||  me.doc.scrollTop() > me.lastTop ){
	//         //向下 或再 页面顶部，放在 头部
	//         me.head.css({ position : 'absolute' });
	//     }else if( me.doc.scrollTop() < me.lastTop  ){
	//         //向上，悬浮
	//         me.head.css({ position : 'fixed' });
	//     }
	//     me.lastTop = me.doc.scrollTop();
	// });
	
	// document.addEventListener("scroll",function () {
	//     var scrolllenth = document.getElementById("F2").getBoundingClientRect().top;
	//     document.getElementById("Header").style.background='rgba(21,0,141,'+scrolllenth+')';
	// });
	// 
	$(document).ready(function(){

		var $root = $('html, body');
		$("Header a.position").on('click',function(){
			//$(this).addClass('selected').siblings().removeClass('selected');
			$root.animate({
		        scrollTop: $( $.attr(this, 'href') ).offset().top
		    }, 500);
		    return false;
		});

		$(window).scroll(function(){
			var top =  $(window).scrollTop();
			if(top <= 100){
				$("header").stop().animate({height:"126px"},200);
				$("header .headerbox").stop().animate({marginTop:"52px"},200);
			} else {
				$("header").stop().animate({height:"74px"},200);
				$("header .headerbox").stop().animate({marginTop:"0px"},200);
			}
			// if(top > 101 || top <= 200){
			// 	$("header").animate({height:"123px"},200);
			// 	$("header .headerbox").animate({marginTop:"49px"},200);
			// }

			for (i = 1;i < 9;i++){       
				if($("#F"+i).offset().top - 400 <= top){ 
					$("#F"+i+i).addClass('selected').siblings().removeClass('selected');
				}
			}         
		});

		// (function($){
		// 	$(window).load(function(){
		// 		$("body").mCustomScrollbar({
		// 			scrollInertia :80,
		// 			scrollButtons:{
		// 				enable:true,
		// 				scrollSpeed:200
		// 			},
		// 			//horizontalScroll : true,
		// 			advanced:{ 
		// 				autoExpandHorizontalScroll:true
		// 			},
		// 		});
		// 	});
		// })(jQuery);
	

	});

</script>
{% endblock %}
