<header id="Header">
	<div class="headerbox">
		<div class="headerrow">
			<div class="logo">
				<img src="/public/img/logo_hk.png">
			</div>
			<div class="linksrow">
				<a id="F11" href="#F1" class="position selected">首頁</a>
				<a id="F22" href="#F2" class="position">方案</a>
				<a id="F33" href="#F3" class="position">挖礦</a>
				<a id="F44" href="#F4" class="position">接口</a>
				<a id="F55" href="#F5" class="position">團隊</a>
				<a id="F66" href="#F6" class="position">路線</a>
				<a id="F77" href="#F7" class="position">案例</a>
				<a id="F88" href="#F8" class="position">聯系</a>
				<div class="lang">
					<a href="/index/en" class="en left" title="Language：English"></a>
					<a href="/index/hk" class="hk left" title="語言：繁體中文"></a>
					<a href="/index/index" class="cn left" title="语言：简体中文"></a>
				</div>
			</div>
		</div>
	</div>
</header>